// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentUserPromptType } from "./CurrentUserPromptType";

export interface AcceptConnection { type: CurrentUserPromptType, client_name: string, logo_uri: string, redirect_uri: string, previously_connected: boolean, }
