// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialOffer } from "./CredentialOffer";
import type { PasswordRequired } from "./CredentialOffer";
import type { Redirect } from "./Redirect";
import type { Selection } from "./Selection";
import type { Warning } from "./Warning";

export type CurrentUserPrompt = Redirect | Warning | Selection | CredentialOffer | PasswordRequired;