// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrentUserPromptType = "redirect" | "warning" | "select-credentials" | "credential-offer";