// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentUserPromptType } from "./CurrentUserPromptType";

export interface Offer { type: CurrentUserPromptType, options: Array<any>, }