[workspace]
resolver = "2"
members = ["identity-wallet", "unime/src-tauri"]

[workspace.dependencies]
tauri = { version = "2.8.2", features = ["protocol-asset", "rustls-tls"] }
tauri-build = "2.4.0"

did_manager = { git = "https://github.com/impierce/did-manager", tag = "v1.0.0-beta.5" }
jsonwebtoken = "9.3"
log = "^0.4"
oid4vc = { git = "https://github.com/impierce/openid4vc", rev = "8b024cb" }
rand = "0.8"
rustls = { version = "0.23", features = ["aws-lc-rs"] }
rustls-platform-verifier = { version = "0.6" }
serde_json = "1.0"
serial_test = "2.0"
tempfile = "3.5.0"
tokio = { version = "1.43.0", features = ["macros"] }
wiremock = "0.5"

# TODO: Remove these patches once configurable TLS is available in `iota-sdk`.
[patch.'https://github.com/iotaledger/iota']
iota-sdk = { git = "https://github.com/impierce/iota", package = "iota-sdk", branch = "temp/fix" }
move-core-types = { git = "https://github.com/impierce/iota", package = "move-core-types", branch = "temp/fix" }
shared-crypto = { git = "https://github.com/impierce/iota", package = "shared-crypto", branch = "temp/fix" }
iota-network-stack = { git = "https://github.com/impierce/iota", package = "iota-network-stack", branch = "temp/fix" }
iota-types = { git = "https://github.com/impierce/iota", package = "iota-types", branch = "temp/fix" }
iota-metrics = { git = "https://github.com/impierce/iota", package = "iota-metrics", branch = "temp/fix" }
move-binary-format = { git = "https://github.com/impierce/iota", package = "move-binary-format", branch = "temp/fix" }
iota-protocol-config = { git = "https://github.com/impierce/iota", package = "iota-protocol-config", branch = "temp/fix" }
move-vm-config = { git = "https://github.com/impierce/iota", package = "move-vm-config", branch = "temp/fix" }
iota-adapter-latest = { git = "https://github.com/impierce/iota", package = "iota-adapter-latest", branch = "temp/fix" }
iota-execution = { git = "https://github.com/impierce/iota", package = "iota-execution", branch = "temp/fix" }

# TODO: **WARNING**: These are temporary patches that allow us to create and validate both `dc+sd-jwt`s and
# `vc+sd-jwt`s, but this is a very hacky workaround. We need to come up with a better long-term solution.
# To see the actual changes, see: https://github.com/iotaledger/identity/compare/v1.6.0-beta.2...impierce:identity.rs:tmp/disable-typ-check?expand=1
[patch.'https://github.com/iotaledger/identity']
identity_credential = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }
identity_iota_core = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }
identity_storage = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }
identity_resolver = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }
identity_jose = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }
identity_document = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }
identity_verification = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }
identity_iota = { git = "https://github.com/impierce/identity.rs", branch = "tmp/disable-typ-check" }

[workspace.package]
name = "unime"
version = "0.11.0"
description = "Identity Wallet for people to manage Decentralized Identities and Verifiable Credentials"
homepage = "https://www.impierce.com/"
authors = ["Impierce Technologies"]
keywords = ["identity", "did", "ssi", "wallet", "siopv2"]
license = "Apache-2.0"
repository = "https://github.com/impierce/identity-wallet"
edition = "2021"
rust-version = "1.76.0"
