[workspace]
resolver = "2"
members = ["identity-wallet", "unime/src-tauri"]

[workspace.dependencies]
tauri = { version = "2.9.2", features = ["protocol-asset", "rustls-tls"] }
tauri-build = "2.5.1"

did_manager = { git = "https://github.com/impierce/did-manager", tag = "v1.0.0-beta.8" }
jsonwebtoken = "9.3"
log = "^0.4"
oauth_tsl = { git = "https://github.com/impierce/oauth-token-status-list", rev = "df371b9" }
oid4vc = { git = "https://github.com/impierce/openid4vc", rev = "dc2c388" }
rand = "0.8"
rustls = { version = "0.23", features = ["aws-lc-rs"] }
rustls-platform-verifier = { version = "0.6" }
serde_json = "1.0"
serial_test = "2.0"
tempfile = "3.5.0"
tokio = { version = "1.46", features = ["macros"] }
wiremock = "0.5"

[patch.crates-io]
# We need this patch because it makes the `Hasher` trait `Send` and `Sync`. See: https://github.com/iotaledger/sd-jwt-payload/compare/main...impierce:sd-jwt-payload:fix/hasher-send-sync
sd-jwt = { git = "https://github.com/impierce/sd-jwt-payload", rev = "f28789a", package = "sd-jwt-payload" }

[workspace.package]
name = "unime"
version = "0.13.2"
description = "Identity Wallet for people to manage Decentralized Identities and Verifiable Credentials"
homepage = "https://www.impierce.com/"
authors = ["Impierce Technologies"]
keywords = ["identity", "did", "ssi", "wallet", "siopv2"]
license = "Apache-2.0"
repository = "https://github.com/impierce/identity-wallet"
edition = "2021"
rust-version = "1.76.0"
