// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connections } from "./connections/Connections";
import type { CurrentUserPrompt } from "./user_prompt/CurrentUserPrompt";
import type { DevMode } from "./dev_mode/DevMode";
import type { DisplayCredential } from "./credentials/DisplayCredential";
import type { HistoryEvent } from "./history/HistoryEvent";
import type { ProfileSettings } from "./profile_settings/ProfileSettings";
import type { SearchResults } from "./search/SearchResults";

export interface AppState { dids: Record<string, string>, connections: Connections, credentials: Array<DisplayCredential>, search_results: SearchResults, profile_settings: ProfileSettings, current_user_prompt: CurrentUserPrompt | null, user_journey: any | null, debug_messages: Array<string>, history: Array<HistoryEvent>, dev_mode: DevMode, }