// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Connection { id: string, client_name: string, url: string, verified: boolean, first_interacted: string, last_interacted: string, }