// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionSorting = { "name_az": { reverse: boolean | null, } } | { "first_interacted_new_old": { reverse: boolean | null, } } | { "last_interacted_new_old": { reverse: boolean | null, } };