// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectionSortMethod = "name_az" | "first_interacted_new_old" | "last_interacted_new_old";