// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CredentialSorting = { "name_az": { reverse: boolean | null, } } | { "issue_date_new_old": { reverse: boolean | null, } } | { "added_date_new_old": { reverse: boolean | null, } };