// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventType } from "./EventType";
import type { HistoryCredential } from "./HistoryCredential";

export interface HistoryEvent { issuer_name: string, event_type: EventType, connection_id: string | null, date: string, credentials: Array<HistoryCredential>, }