// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locale } from "./Locale";
import type { Profile } from "./Profile";

export interface ProfileSettings { locale: Locale, profile: Profile | null, default_did_method: string, }