// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSortMethod } from "./ConnectionSortMethod";
import type { CredentialSortMethod } from "./CredentialSortMethod";
import type { Preferences } from "./Preferences";

export interface SortingPreferences { credentials: Preferences<CredentialSortMethod>, connections: Preferences<ConnectionSortMethod>, }