// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSortMethod } from "./ConnectionSortMethod";
import type { CredentialSortMethod } from "./CredentialSortMethod";

export interface SortingPreferences { credential_sort_method: CredentialSortMethod | null, credential_reverse: boolean | null, credentials_sorted: Array<string>, connection_sort_method: ConnectionSortMethod | null, connection_reverse: boolean | null, connections_sorted: Array<string>, }