// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CredentialStatusData { status: string, idx: bigint, uri: string, last_checked: string, }