// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CredentialStatus { status: 'VALID' | 'INVALID' | 'SUSPENDED' | 'UNDEFINED', last_checked: string, reachable: boolean, }