// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CredentialStatusData { status: string, status_list_uri: string, status_list_index: number, last_checked: string, }