// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CredentialMetadata { is_favorite: boolean, date_added: string, date_issued: string, }