// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialMetadata } from "./CredentialMetadata";
import type { CredentialStatusData } from "./CredentialStatusData";
import type { DisplayClaim } from "./DisplayClaim";

export interface DisplayCredential { id: string, format: { format: string }, issuer_name: string, data: any, display_claims: Array<DisplayClaim>, metadata: CredentialMetadata, connection_id?: string, display_name: string, credential_status: CredentialStatusData | null, }