// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialMetadata } from "./CredentialMetadata";

export interface DisplayCredential { id: string, format: string, issuer_name: string, data: any, metadata: CredentialMetadata, connection_id?: string, display_name: string, }