// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EcosystemProfile } from "../user_prompt/EcosystemProfile";
import type { LinkedVerifiableCredentialData } from "../user_prompt/LinkedVerifiableCredentialData";
import type { ValidationStatus } from "../user_prompt/ValidationStatus";

export interface Connection { id: string, name: string, url: string, did: string, verified: boolean, first_interacted: string, last_interacted: string, linked_verifiable_presentations?: Array<LinkedVerifiableCredentialData>, ecosystems?: Array<EcosystemProfile>, domain_validation?: [ValidationStatus, string], }