// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BackupPreview { id: string, appVersion: string, profileName: string | null, credentials: number, connections: number, assets: number, }