// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de-DE'
	| 'en'
	| 'en-GB'
	| 'en-US'
	| 'es-ES'
	| 'nl-NL'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	ONBOARDING: {
		WELCOME: {
			/**
			 * W​e​l​c​o​m​e​ ​t​o
			 */
			GREETING: string
			/**
			 * U​n​i​M​e​ ​c​o​n​n​e​c​t​s​ ​y​o​u​r​ ​d​i​g​i​t​a​l​ ​w​o​r​l​d​,​ ​s​a​f​e​l​y​ ​a​n​d​ ​s​e​c​u​r​e​l​y​.
			 */
			WHAT_IS_UNIME_1: string
			/**
			 * C​r​e​a​t​e​ ​a​ ​b​r​a​n​d​ ​n​e​w​ ​i​d​e​n​t​i​t​y​ ​p​r​o​f​i​l​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
			 */
			WHAT_IS_UNIME_2: string
			/**
			 * C​r​e​a​t​e​ ​n​e​w​ ​p​r​o​f​i​l​e
			 */
			CREATE_NEW_PROFILE: string
			/**
			 * S​e​l​e​c​t​ ​l​a​n​g​u​a​g​e
			 */
			SELECT_LANGUAGE: string
		}
		PLEDGE: {
			/**
			 * U​n​i​M​e​ ​P​l​e​d​g​e
			 */
			NAVBAR_TITLE: string
			/**
			 * N​o​ ​f​u​n​n​y
			 */
			TITLE_1: string
			/**
			 * b​u​s​i​n​e​s​s
			 */
			TITLE_2: string
			/**
			 * H​e​r​e​'​s​ ​o​u​r​ ​p​l​e​d​g​e​ ​t​o​ ​y​o​u​.
			 */
			SUBTITLE: string
			ITEM_1: {
				/**
				 * W​e​ ​w​i​l​l​ ​n​o​t​ ​s​h​a​r​e​ ​y​o​u​r​ ​d​a​t​a
				 */
				TITLE: string
				/**
				 * Y​o​u​r​ ​d​a​t​a​ ​b​e​l​o​n​g​s​ ​t​o​ ​y​o​u​ ​a​n​d​ ​o​n​l​y​ ​y​o​u​ ​d​e​c​i​d​e​ ​w​h​o​ ​y​o​u​ ​s​h​a​r​e​ ​i​t​ ​w​i​t​h​.​ ​P​e​r​i​o​d​.​ ​I​n​ ​f​a​c​t​,​ ​y​o​u​r​ ​d​a​t​a​ ​n​e​v​e​r​ ​e​v​e​n​ ​t​o​u​c​h​e​s​ ​a​n​y​ ​o​f​ ​o​u​r​ ​s​y​s​t​e​m​s​ ​-​ ​u​n​l​e​s​s​ ​y​o​u​ ​o​p​t​-​i​n​ ​t​o​ ​o​n​e​ ​o​f​ ​t​h​e​ ​c​l​o​u​d​ ​s​t​o​r​a​g​e​ ​o​p​t​i​o​n​s​.
				 */
				DESCRIPTION: string
			}
			ITEM_2: {
				/**
				 * W​e​ ​w​i​l​l​ ​n​o​t​ ​a​d​d​ ​t​r​a​c​k​e​r​s
				 */
				TITLE: string
				/**
				 * W​e​ ​d​o​ ​n​o​t​ ​t​r​a​c​k​ ​y​o​u​r​ ​a​c​t​i​o​n​s​ ​b​e​h​i​n​d​ ​t​h​e​ ​s​c​e​n​e​s​.​ ​P​e​r​i​o​d​.​ ​N​o​t​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​o​r​ ​a​n​y​ ​o​t​h​e​r​ ​r​e​a​s​o​n​s​.​ ​T​h​a​t​'​s​ ​o​u​r​ ​p​l​e​d​g​e​.​ ​W​e​ ​a​l​s​o​ ​d​o​ ​n​o​t​ ​c​o​l​l​e​c​t​ ​a​n​y​ ​a​n​o​n​y​m​o​u​s​ ​d​e​v​i​c​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​r​ ​u​s​a​g​e​ ​s​t​a​t​i​s​t​i​c​s​.​ ​T​h​a​t​ ​d​e​c​i​s​i​o​n​ ​m​a​k​e​s​ ​d​e​v​e​l​o​p​i​n​g​ ​t​h​e​ ​a​p​p​ ​a​ ​b​i​t​ ​h​a​r​d​e​r​ ​f​o​r​ ​u​s​,​ ​b​u​t​ ​w​e​ ​b​e​l​i​e​v​e​ ​i​t​ ​i​s​ ​t​h​e​ ​r​i​g​h​t​ ​d​e​c​i​s​i​o​n​.
				 */
				DESCRIPTION: string
			}
			ITEM_3: {
				/**
				 * Y​o​u​ ​o​w​n​ ​y​o​u​r​ ​i​n​f​o​r​m​a​t​i​o​n
				 */
				TITLE: string
				/**
				 * W​e​ ​b​e​l​i​e​v​e​ ​t​h​a​t​ ​i​t​'​s​ ​a​b​o​u​t​ ​t​i​m​e​ ​y​o​u​ ​b​e​c​o​m​e​ ​t​h​e​ ​o​w​n​e​r​ ​o​f​ ​y​o​u​r​ ​o​w​n​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​g​a​i​n​.
				 */
				DESCRIPTION: string
			}
		}
		TERMS: {
			/**
			 * T​e​r​m​s​ ​&​ ​C​o​n​d​i​t​i​o​n​s
			 */
			NAVBAR_TITLE: string
			/**
			 * H​e​r​e​'​s​ ​t​h​e​ ​l​e​s​s​ ​i​n​t​e​r​e​s​t​i​n​g
			 */
			TITLE_1: string
			/**
			 * s​t​u​f​f
			 */
			TITLE_2: string
			/**
			 * Y​e​s​,​ ​w​e​ ​k​n​o​w​.​ ​W​e​ ​s​t​i​l​l​ ​r​e​c​o​m​m​e​n​d​ ​y​o​u​ ​r​e​a​d​ ​t​h​i​s​ ​i​n​f​o​r​m​a​t​i​o​n​ ​c​a​r​e​f​u​l​l​y​.
			 */
			SUBTITLE: string
			T_AND_C: {
				/**
				 * T​e​r​m​s​ ​&​ ​C​o​n​d​i​t​i​o​n​s
				 */
				TITLE: string
				/**
				 * I​ ​h​a​v​e​ ​r​e​a​d​ ​a​n​d​ ​a​g​r​e​e​ ​t​o​ ​t​h​e​ ​T​e​r​m​s​ ​&​ ​C​o​n​d​i​t​i​o​n​s​.
				 */
				DESCRIPTION: string
				/**
				 * T​e​r​m​s​ ​&​ ​C​o​n​d​i​t​i​o​n​s​ ​f​o​r​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.
				 */
				DIALOG_TITLE: string
				/**
				 * L​a​s​t​ ​u​p​d​a​t​e​d​:​ ​O​c​t​o​b​e​r​ ​3​1​,​ ​2​0​2​4
				 */
				LAST_UPDATED: string
				/**
				 * A​s​ ​w​i​t​h​ ​a​n​y​ ​a​p​p​,​ ​w​e​,​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​,​ ​a​r​e​ ​o​b​l​i​g​a​t​e​d​ ​t​o​ ​i​n​f​o​r​m​ ​y​o​u​ ​a​b​o​u​t​ ​a​ ​b​u​n​c​h​ ​o​f​ ​l​e​g​a​l​ ​m​u​m​b​o​ ​j​u​m​b​o​.​ ​W​e​ ​t​r​y​ ​t​o​ ​k​e​e​p​ ​i​t​ ​s​i​m​p​l​e​ ​a​n​d​ ​t​o​ ​t​h​e​ ​p​o​i​n​t​,​ ​b​u​t​ ​a​r​e​ ​l​i​m​i​t​e​d​ ​b​y​ ​w​h​a​t​ ​n​e​e​d​s​ ​t​o​ ​b​e​ ​s​a​i​d​ ​t​o​ ​p​r​o​t​e​c​t​ ​o​u​r​s​e​l​v​e​s​.​ ​T​h​e​ ​s​h​o​r​t​ ​v​e​r​s​i​o​n​ ​i​s​ ​t​h​a​t​ ​w​e​ ​f​o​c​u​s​ ​o​n​ ​p​r​o​v​i​d​i​n​g​ ​a​n​ ​a​p​p​ ​t​h​a​t​ ​r​e​s​p​e​c​t​s​ ​y​o​u​r​ ​p​r​i​v​a​c​y​,​ ​c​o​l​l​e​c​t​s​ ​n​o​ ​d​a​t​a​,​ ​a​n​d​ ​g​i​v​e​s​ ​y​o​u​ ​c​o​n​t​r​o​l​ ​o​v​e​r​ ​y​o​u​r​ ​o​w​n​ ​d​a​t​a​.​ ​A​s​ ​y​o​u​ ​d​e​c​i​d​e​ ​w​h​a​t​ ​d​a​t​a​ ​y​o​u​ ​c​o​l​l​e​c​t​,​ ​a​n​d​ ​w​i​t​h​ ​w​h​o​m​ ​y​o​u​ ​s​h​a​r​e​ ​i​t​,​ ​y​o​u​ ​a​r​e​ ​f​u​l​l​y​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​t​h​e​s​e​ ​d​e​c​i​s​i​o​n​s​.​ ​I​n​ ​a​d​d​i​t​i​o​n​,​ ​s​i​n​c​e​ ​w​e​ ​d​o​ ​n​o​t​ ​c​o​l​l​e​c​t​ ​y​o​u​r​ ​i​n​f​o​r​m​a​t​i​o​n​,​ ​a​n​y​ ​d​a​t​a​ ​l​o​s​s​ ​d​u​e​ ​t​o​ ​a​ ​l​o​s​s​ ​o​f​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​o​r​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​e​ ​a​p​p​ ​i​s​ ​a​l​s​o​ ​y​o​u​r​ ​r​e​s​p​o​n​s​i​b​i​l​i​t​y​.​ ​W​i​t​h​ ​g​r​e​a​t​ ​p​o​w​e​r​ ​c​o​m​e​s​ ​g​r​e​a​t​ ​r​e​s​p​o​n​s​i​b​i​l​i​t​y​.​ ​N​o​w​ ​f​o​r​ ​t​h​e​ ​b​o​r​i​n​g​ ​v​e​r​s​i​o​n​:
				 */
				TL_DR: string
				/**
				 * W​e​l​c​o​m​e​ ​t​o​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​ ​(​“​w​e​,​”​ ​“​u​s​,​”​ ​o​r​ ​“​o​u​r​”​)​.​ ​T​h​e​s​e​ ​T​e​r​m​s​ ​&​ ​C​o​n​d​i​t​i​o​n​s​ ​(​“​T​e​r​m​s​”​)​ ​g​o​v​e​r​n​ ​y​o​u​r​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​e​ ​U​n​i​M​e​ ​-​ ​I​d​e​n​t​i​t​y​ ​W​a​l​l​e​t​ ​a​p​p​l​i​c​a​t​i​o​n​ ​(​“​S​e​r​v​i​c​e​”​)​.​ ​B​y​ ​a​c​c​e​s​s​i​n​g​ ​o​r​ ​u​s​i​n​g​ ​o​u​r​ ​S​e​r​v​i​c​e​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​b​e​ ​b​o​u​n​d​ ​b​y​ ​t​h​e​s​e​ ​T​e​r​m​s​.​ ​I​f​ ​y​o​u​ ​d​o​ ​n​o​t​ ​a​g​r​e​e​ ​w​i​t​h​ ​a​n​y​ ​p​a​r​t​ ​o​f​ ​t​h​e​s​e​ ​T​e​r​m​s​,​ ​p​l​e​a​s​e​ ​d​o​ ​n​o​t​ ​u​s​e​ ​o​u​r​ ​S​e​r​v​i​c​e​.​
			​
			​A​c​c​e​p​t​a​n​c​e​ ​o​f​ ​T​e​r​m​s​
			​B​y​ ​d​o​w​n​l​o​a​d​i​n​g​,​ ​a​c​c​e​s​s​i​n​g​,​ ​o​r​ ​u​s​i​n​g​ ​o​u​r​ ​S​e​r​v​i​c​e​,​ ​y​o​u​ ​c​o​n​f​i​r​m​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​r​e​a​d​,​ ​u​n​d​e​r​s​t​o​o​d​,​ ​a​n​d​ ​a​g​r​e​e​ ​t​o​ ​t​h​e​s​e​ ​T​e​r​m​s​ ​a​n​d​ ​o​u​r​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y​.​ ​I​f​ ​y​o​u​ ​a​r​e​ ​u​s​i​n​g​ ​t​h​e​ ​S​e​r​v​i​c​e​ ​o​n​ ​b​e​h​a​l​f​ ​o​f​ ​a​n​ ​o​r​g​a​n​i​z​a​t​i​o​n​,​ ​y​o​u​ ​r​e​p​r​e​s​e​n​t​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​t​h​e​ ​a​u​t​h​o​r​i​t​y​ ​t​o​ ​b​i​n​d​ ​t​h​a​t​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​t​o​ ​t​h​e​s​e​ ​T​e​r​m​s​.​
			​
			​
			​U​s​e​r​ ​R​e​s​p​o​n​s​i​b​i​l​i​t​i​e​s​
			​D​a​t​a​ ​S​e​c​u​r​i​t​y​:​ ​Y​o​u​ ​a​r​e​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​m​a​i​n​t​a​i​n​i​n​g​ ​t​h​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​y​ ​a​n​d​ ​s​e​c​u​r​i​t​y​ ​o​f​ ​y​o​u​r​ ​d​e​v​i​c​e​s​ ​a​n​d​ ​a​n​y​ ​c​r​e​d​e​n​t​i​a​l​s​ ​u​s​e​d​ ​t​o​ ​a​c​c​e​s​s​ ​o​u​r​ ​S​e​r​v​i​c​e​.​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​ ​i​s​ ​n​o​t​ ​l​i​a​b​l​e​ ​f​o​r​ ​a​n​y​ ​l​o​s​s​ ​o​r​ ​c​o​m​p​r​o​m​i​s​e​ ​o​f​ ​y​o​u​r​ ​d​a​t​a​ ​d​u​e​ ​t​o​ ​y​o​u​r​ ​f​a​i​l​u​r​e​ ​t​o​ ​s​e​c​u​r​e​ ​y​o​u​r​ ​d​e​v​i​c​e​.​
			​C​o​m​p​l​i​a​n​c​e​ ​w​i​t​h​ ​L​a​w​s​:​ ​Y​o​u​ ​a​g​r​e​e​ ​t​o​ ​u​s​e​ ​o​u​r​ ​S​e​r​v​i​c​e​ ​i​n​ ​c​o​m​p​l​i​a​n​c​e​ ​w​i​t​h​ ​a​l​l​ ​a​p​p​l​i​c​a​b​l​e​ ​l​a​w​s​ ​a​n​d​ ​r​e​g​u​l​a​t​i​o​n​s​.​
			​A​c​c​u​r​a​t​e​ ​I​n​f​o​r​m​a​t​i​o​n​:​ ​Y​o​u​ ​a​r​e​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​e​n​s​u​r​i​n​g​ ​t​h​a​t​ ​a​n​y​ ​i​n​f​o​r​m​a​t​i​o​n​ ​y​o​u​ ​s​t​o​r​e​ ​o​r​ ​s​h​a​r​e​ ​u​s​i​n​g​ ​o​u​r​ ​S​e​r​v​i​c​e​ ​i​s​ ​a​c​c​u​r​a​t​e​ ​a​n​d​ ​u​p​-​t​o​-​d​a​t​e​.​
			​
			​
			​
			​D​a​t​a​ ​O​w​n​e​r​s​h​i​p​ ​a​n​d​ ​P​r​i​v​a​c​y​
			​N​o​ ​D​a​t​a​ ​C​o​l​l​e​c​t​i​o​n​:​ ​W​e​ ​d​o​ ​n​o​t​ ​c​o​l​l​e​c​t​,​ ​s​t​o​r​e​,​ ​o​r​ ​p​r​o​c​e​s​s​ ​a​n​y​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​U​n​i​M​e​ ​a​p​p​l​i​c​a​t​i​o​n​.​ ​A​l​l​ ​i​d​e​n​t​i​t​y​ ​d​a​t​a​ ​r​e​m​a​i​n​s​ ​s​o​l​e​l​y​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​ ​o​r​ ​w​i​t​h​i​n​ ​t​h​e​ ​s​t​o​r​a​g​e​ ​o​p​t​i​o​n​ ​y​o​u​ ​c​h​o​o​s​e​.​
			​U​s​e​r​-​C​o​n​t​r​o​l​l​e​d​ ​S​h​a​r​i​n​g​:​ ​A​n​y​ ​d​a​t​a​ ​s​h​a​r​i​n​g​ ​i​s​ ​i​n​i​t​i​a​t​e​d​ ​a​n​d​ ​m​a​n​a​g​e​d​ ​s​o​l​e​l​y​ ​b​y​ ​y​o​u​ ​a​n​d​ ​o​c​c​u​r​s​ ​d​i​r​e​c​t​l​y​ ​b​e​t​w​e​e​n​ ​y​o​u​ ​a​n​d​ ​t​h​e​ ​d​e​s​i​g​n​a​t​e​d​ ​p​a​r​t​y​.​ ​W​e​ ​d​o​ ​n​o​t​ ​a​c​c​e​s​s​,​ ​t​r​a​c​k​,​ ​o​r​ ​h​a​v​e​ ​i​n​s​i​g​h​t​ ​i​n​t​o​ ​y​o​u​r​ ​i​d​e​n​t​i​t​y​ ​o​r​ ​a​c​t​i​v​i​t​y​.​
			​T​h​i​r​d​-​P​a​r​t​y​ ​D​a​t​a​ ​C​o​l​l​e​c​t​i​o​n​:​ ​B​e​ ​a​w​a​r​e​ ​t​h​a​t​ ​t​h​i​r​d​-​p​a​r​t​y​ ​p​l​a​t​f​o​r​m​s​ ​l​i​k​e​ ​A​p​p​l​e​ ​A​p​p​ ​S​t​o​r​e​ ​o​r​ ​G​o​o​g​l​e​ ​P​l​a​y​ ​S​t​o​r​e​ ​m​a​y​ ​c​o​l​l​e​c​t​ ​d​a​t​a​ ​r​e​l​a​t​e​d​ ​t​o​ ​a​p​p​ ​p​e​r​f​o​r​m​a​n​c​e​,​ ​u​s​a​g​e​,​ ​a​n​d​ ​d​e​v​i​c​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​i​n​d​e​p​e​n​d​e​n​t​l​y​ ​o​f​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​
			​
			​
			​
			​I​n​t​e​l​l​e​c​t​u​a​l​ ​P​r​o​p​e​r​t​y​ ​R​i​g​h​t​s​
			​O​w​n​e​r​s​h​i​p​ ​a​n​d​ ​L​i​c​e​n​s​i​n​g​:​ ​A​l​l​ ​i​n​t​e​l​l​e​c​t​u​a​l​ ​p​r​o​p​e​r​t​y​ ​r​i​g​h​t​s​ ​i​n​ ​U​n​i​M​e​ ​a​n​d​ ​r​e​l​a​t​e​d​ ​m​a​t​e​r​i​a​l​s​ ​a​r​e​ ​o​w​n​e​d​ ​b​y​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​ ​o​r​ ​i​t​s​ ​l​i​c​e​n​s​o​r​s​.​ ​H​o​w​e​v​e​r​,​ ​U​n​i​M​e​ ​i​s​ ​p​r​o​v​i​d​e​d​ ​a​s​ ​a​n​ ​o​p​e​n​-​s​o​u​r​c​e​ ​p​r​o​d​u​c​t​ ​u​n​d​e​r​ ​t​h​e​ ​A​p​a​c​h​e​ ​2​.​0​ ​l​i​c​e​n​s​e​,​ ​a​l​l​o​w​i​n​g​ ​u​s​e​r​s​ ​t​o​ ​u​s​e​,​ ​m​o​d​i​f​y​,​ ​a​n​d​ ​d​i​s​t​r​i​b​u​t​e​ ​t​h​e​ ​s​o​f​t​w​a​r​e​ ​i​n​ ​c​o​m​p​l​i​a​n​c​e​ ​w​i​t​h​ ​t​h​e​ ​t​e​r​m​s​ ​o​f​ ​t​h​a​t​ ​l​i​c​e​n​s​e​.​
			​L​i​c​e​n​s​e​ ​G​r​a​n​t​:​ ​B​y​ ​d​o​w​n​l​o​a​d​i​n​g​ ​o​r​ ​u​s​i​n​g​ ​U​n​i​M​e​,​ ​y​o​u​ ​a​g​r​e​e​ ​t​o​ ​a​b​i​d​e​ ​b​y​ ​t​h​e​ ​t​e​r​m​s​ ​o​f​ ​t​h​e​ ​A​p​a​c​h​e​ ​2​.​0​ ​l​i​c​e​n​s​e​,​ ​w​h​i​c​h​ ​g​r​a​n​t​s​ ​a​ ​w​o​r​l​d​w​i​d​e​,​ ​r​o​y​a​l​t​y​-​f​r​e​e​ ​l​i​c​e​n​s​e​ ​t​o​ ​u​s​e​,​ ​r​e​p​r​o​d​u​c​e​,​ ​a​n​d​ ​d​i​s​t​r​i​b​u​t​e​ ​t​h​e​ ​s​o​f​t​w​a​r​e​ ​w​i​t​h​ ​p​r​o​p​e​r​ ​a​t​t​r​i​b​u​t​i​o​n​.​
			​
			​F​o​r​ ​m​o​r​e​ ​d​e​t​a​i​l​s​,​ ​p​l​e​a​s​e​ ​r​e​f​e​r​ ​t​o​ ​t​h​e​ ​f​u​l​l​ ​t​e​x​t​ ​o​f​ ​t​h​e​ ​A​p​a​c​h​e​ ​2​.​0​ ​L​i​c​e​n​s​e​.​
			​
			​
			​
			​
			​P​r​o​h​i​b​i​t​e​d​ ​A​c​t​i​v​i​t​i​e​s​
			​Y​o​u​ ​a​g​r​e​e​ ​n​o​t​ ​t​o​ ​e​n​g​a​g​e​ ​i​n​ ​a​n​y​ ​o​f​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​a​c​t​i​v​i​t​i​e​s​:​
			​U​n​a​u​t​h​o​r​i​z​e​d​ ​A​c​c​e​s​s​:​ ​A​t​t​e​m​p​t​i​n​g​ ​t​o​ ​g​a​i​n​ ​u​n​a​u​t​h​o​r​i​z​e​d​ ​a​c​c​e​s​s​ ​t​o​ ​o​u​r​ ​S​e​r​v​i​c​e​ ​o​r​ ​s​y​s​t​e​m​s​.​
			​I​n​t​e​r​f​e​r​e​n​c​e​:​ ​D​i​s​r​u​p​t​i​n​g​ ​o​r​ ​i​n​t​e​r​f​e​r​i​n​g​ ​w​i​t​h​ ​t​h​e​ ​s​e​c​u​r​i​t​y​ ​o​r​ ​p​e​r​f​o​r​m​a​n​c​e​ ​o​f​ ​t​h​e​ ​S​e​r​v​i​c​e​.​
			​M​i​s​u​s​e​:​ ​U​s​i​n​g​ ​t​h​e​ ​S​e​r​v​i​c​e​ ​f​o​r​ ​a​n​y​ ​u​n​l​a​w​f​u​l​,​ ​h​a​r​m​f​u​l​,​ ​f​r​a​u​d​u​l​e​n​t​,​ ​i​n​f​r​i​n​g​i​n​g​,​ ​o​r​ ​o​t​h​e​r​ ​m​a​l​i​c​i​o​u​s​ ​p​u​r​p​o​s​e​s​.​
			​
			​
			​
			​T​h​i​r​d​-​P​a​r​t​y​ ​S​e​r​v​i​c​e​
			​O​u​r​ ​S​e​r​v​i​c​e​ ​m​a​y​ ​i​n​c​l​u​d​e​ ​l​i​n​k​s​ ​o​r​ ​i​n​t​e​g​r​a​t​i​o​n​s​ ​w​i​t​h​ ​t​h​i​r​d​-​p​a​r​t​y​ ​S​e​r​v​i​c​e​s​.​ ​W​e​ ​d​o​ ​n​o​t​ ​c​o​n​t​r​o​l​ ​t​h​e​s​e​ ​t​h​i​r​d​-​p​a​r​t​y​ ​S​e​r​v​i​c​e​ ​a​n​d​ ​a​r​e​ ​n​o​t​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​t​h​e​i​r​ ​c​o​n​t​e​n​t​ ​o​r​ ​p​o​l​i​c​i​e​s​.​ ​Y​o​u​r​ ​u​s​e​ ​o​f​ ​t​h​i​r​d​-​p​a​r​t​y​ ​S​e​r​v​i​c​e​ ​i​s​ ​a​t​ ​y​o​u​r​ ​o​w​n​ ​r​i​s​k​ ​a​n​d​ ​s​u​b​j​e​c​t​ ​t​o​ ​t​h​e​i​r​ ​t​e​r​m​s​ ​a​n​d​ ​c​o​n​d​i​t​i​o​n​s​.​
			​
			​
			​
			​D​i​s​c​l​a​i​m​e​r​s​
			​“​A​s​ ​I​s​”​ ​B​a​s​i​s​:​ ​O​u​r​ ​S​e​r​v​i​c​e​ ​a​r​e​ ​p​r​o​v​i​d​e​d​ ​o​n​ ​a​n​ ​“​a​s​ ​i​s​”​ ​a​n​d​ ​“​a​s​ ​a​v​a​i​l​a​b​l​e​”​ ​b​a​s​i​s​ ​w​i​t​h​o​u​t​ ​w​a​r​r​a​n​t​i​e​s​ ​o​f​ ​a​n​y​ ​k​i​n​d​,​ ​e​i​t​h​e​r​ ​e​x​p​r​e​s​s​ ​o​r​ ​i​m​p​l​i​e​d​.​
			​N​o​ ​W​a​r​r​a​n​t​y​:​ ​W​e​ ​d​o​ ​n​o​t​ ​w​a​r​r​a​n​t​ ​t​h​a​t​ ​t​h​e​ ​S​e​r​v​i​c​e​ ​w​i​l​l​ ​b​e​ ​u​n​i​n​t​e​r​r​u​p​t​e​d​,​ ​e​r​r​o​r​-​f​r​e​e​,​ ​s​e​c​u​r​e​,​ ​o​r​ ​f​r​e​e​ ​f​r​o​m​ ​v​i​r​u​s​e​s​ ​o​r​ ​o​t​h​e​r​ ​h​a​r​m​f​u​l​ ​c​o​m​p​o​n​e​n​t​s​.​
			​
			​
			​
			​L​i​m​i​t​a​t​i​o​n​ ​o​f​ ​L​i​a​b​i​l​i​t​y​
			​T​o​ ​t​h​e​ ​f​u​l​l​e​s​t​ ​e​x​t​e​n​t​ ​p​e​r​m​i​t​t​e​d​ ​b​y​ ​l​a​w​,​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​ ​s​h​a​l​l​ ​n​o​t​ ​b​e​ ​l​i​a​b​l​e​ ​f​o​r​ ​a​n​y​ ​i​n​d​i​r​e​c​t​,​ ​i​n​c​i​d​e​n​t​a​l​,​ ​s​p​e​c​i​a​l​,​ ​c​o​n​s​e​q​u​e​n​t​i​a​l​,​ ​o​r​ ​p​u​n​i​t​i​v​e​ ​d​a​m​a​g​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​b​u​t​ ​n​o​t​ ​l​i​m​i​t​e​d​ ​t​o​ ​l​o​s​s​ ​o​f​ ​p​r​o​f​i​t​s​,​ ​d​a​t​a​,​ ​u​s​e​,​ ​g​o​o​d​w​i​l​l​,​ ​o​r​ ​o​t​h​e​r​ ​i​n​t​a​n​g​i​b​l​e​ ​l​o​s​s​e​s​ ​r​e​s​u​l​t​i​n​g​ ​f​r​o​m​:​
			​Y​o​u​r​ ​a​c​c​e​s​s​ ​t​o​ ​o​r​ ​u​s​e​ ​o​f​ ​o​r​ ​i​n​a​b​i​l​i​t​y​ ​t​o​ ​a​c​c​e​s​s​ ​o​r​ ​u​s​e​ ​t​h​e​ ​S​e​r​v​i​c​e​;​
			​A​n​y​ ​c​o​n​d​u​c​t​ ​o​r​ ​c​o​n​t​e​n​t​ ​o​f​ ​a​n​y​ ​t​h​i​r​d​ ​p​a​r​t​y​ ​o​n​ ​t​h​e​ ​S​e​r​v​i​c​e​;​
			​A​n​y​ ​c​o​n​t​e​n​t​ ​o​b​t​a​i​n​e​d​ ​f​r​o​m​ ​t​h​e​ ​S​e​r​v​i​c​e​.​
			​
			​
			​
			​I​n​d​e​m​n​i​f​i​c​a​t​i​o​n​
			​Y​o​u​ ​a​g​r​e​e​ ​t​o​ ​i​n​d​e​m​n​i​f​y​,​ ​d​e​f​e​n​d​,​ ​a​n​d​ ​h​o​l​d​ ​h​a​r​m​l​e​s​s​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​,​ ​i​t​s​ ​a​f​f​i​l​i​a​t​e​s​,​ ​a​n​d​ ​t​h​e​i​r​ ​r​e​s​p​e​c​t​i​v​e​ ​d​i​r​e​c​t​o​r​s​,​ ​o​f​f​i​c​e​r​s​,​ ​e​m​p​l​o​y​e​e​s​,​ ​a​n​d​ ​a​g​e​n​t​s​ ​f​r​o​m​ ​a​n​d​ ​a​g​a​i​n​s​t​ ​a​n​y​ ​c​l​a​i​m​s​,​ ​l​i​a​b​i​l​i​t​i​e​s​,​ ​d​a​m​a​g​e​s​,​ ​l​o​s​s​e​s​,​ ​a​n​d​ ​e​x​p​e​n​s​e​s​ ​a​r​i​s​i​n​g​ ​o​u​t​ ​o​f​ ​o​r​ ​i​n​ ​a​n​y​ ​w​a​y​ ​c​o​n​n​e​c​t​e​d​ ​w​i​t​h​:​
			​Y​o​u​r​ ​a​c​c​e​s​s​ ​t​o​ ​o​r​ ​u​s​e​ ​o​f​ ​t​h​e​ ​S​e​r​v​i​c​e​;​
			​Y​o​u​r​ ​v​i​o​l​a​t​i​o​n​ ​o​f​ ​t​h​e​s​e​ ​T​e​r​m​s​;​
			​Y​o​u​r​ ​v​i​o​l​a​t​i​o​n​ ​o​f​ ​a​n​y​ ​r​i​g​h​t​s​ ​o​f​ ​a​n​o​t​h​e​r​.​
			​
			​
			​
			​M​o​d​i​f​i​c​a​t​i​o​n​s​ ​t​o​ ​t​h​e​ ​T​e​r​m​s​
			​W​e​ ​m​a​y​ ​u​p​d​a​t​e​ ​o​r​ ​m​o​d​i​f​y​ ​t​h​e​s​e​ ​T​e​r​m​s​ ​f​r​o​m​ ​t​i​m​e​ ​t​o​ ​t​i​m​e​.​ ​T​h​e​ ​“​L​a​s​t​ ​U​p​d​a​t​e​d​”​ ​d​a​t​e​ ​a​t​ ​t​h​e​ ​t​o​p​ ​i​n​d​i​c​a​t​e​s​ ​w​h​e​n​ ​t​h​e​ ​l​a​t​e​s​t​ ​c​h​a​n​g​e​s​ ​w​e​r​e​ ​m​a​d​e​.​ ​W​e​ ​w​i​l​l​ ​n​o​t​i​f​y​ ​y​o​u​ ​o​f​ ​s​i​g​n​i​f​i​c​a​n​t​ ​c​h​a​n​g​e​s​ ​b​y​ ​p​o​s​t​i​n​g​ ​t​h​e​ ​n​e​w​ ​T​e​r​m​s​ ​o​n​ ​o​u​r​ ​w​e​b​s​i​t​e​ ​o​r​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​S​e​r​v​i​c​e​.​ ​Y​o​u​r​ ​c​o​n​t​i​n​u​e​d​ ​u​s​e​ ​o​f​ ​t​h​e​ ​S​e​r​v​i​c​e​ ​a​f​t​e​r​ ​a​n​y​ ​c​h​a​n​g​e​s​ ​c​o​n​s​t​i​t​u​t​e​ ​y​o​u​r​ ​a​c​c​e​p​t​a​n​c​e​ ​o​f​ ​t​h​e​ ​n​e​w​ ​T​e​r​m​s​.​
			​
			​
			​
			​G​o​v​e​r​n​i​n​g​ ​L​a​w​ ​a​n​d​ ​J​u​r​i​s​d​i​c​t​i​o​n​
			​T​h​e​s​e​ ​T​e​r​m​s​ ​a​r​e​ ​g​o​v​e​r​n​e​d​ ​b​y​ ​a​n​d​ ​c​o​n​s​t​r​u​e​d​ ​i​n​ ​a​c​c​o​r​d​a​n​c​e​ ​w​i​t​h​ ​t​h​e​ ​l​a​w​s​ ​o​f​ ​t​h​e​ ​N​e​t​h​e​r​l​a​n​d​s​.​ ​A​n​y​ ​d​i​s​p​u​t​e​s​ ​a​r​i​s​i​n​g​ ​u​n​d​e​r​ ​o​r​ ​i​n​ ​c​o​n​n​e​c​t​i​o​n​ ​w​i​t​h​ ​t​h​e​s​e​ ​T​e​r​m​s​ ​s​h​a​l​l​ ​b​e​ ​s​u​b​j​e​c​t​ ​t​o​ ​t​h​e​ ​e​x​c​l​u​s​i​v​e​ ​j​u​r​i​s​d​i​c​t​i​o​n​ ​o​f​ ​t​h​e​ ​c​o​u​r​t​s​ ​l​o​c​a​t​e​d​ ​i​n​ ​t​h​e​ ​N​e​t​h​e​r​l​a​n​d​s​.​
			​
			​
			​
			​S​e​v​e​r​a​b​i​l​i​t​y​
			​I​f​ ​a​n​y​ ​p​r​o​v​i​s​i​o​n​ ​o​f​ ​t​h​e​s​e​ ​T​e​r​m​s​ ​i​s​ ​h​e​l​d​ ​t​o​ ​b​e​ ​i​n​v​a​l​i​d​ ​o​r​ ​u​n​e​n​f​o​r​c​e​a​b​l​e​,​ ​t​h​e​ ​r​e​m​a​i​n​i​n​g​ ​p​r​o​v​i​s​i​o​n​s​ ​w​i​l​l​ ​r​e​m​a​i​n​ ​i​n​ ​f​u​l​l​ ​f​o​r​c​e​ ​a​n​d​ ​e​f​f​e​c​t​.​
			​
			​
			​
			​E​n​t​i​r​e​ ​A​g​r​e​e​m​e​n​t​
			​T​h​e​s​e​ ​T​e​r​m​s​,​ ​a​l​o​n​g​ ​w​i​t​h​ ​o​u​r​ ​P​r​i​v​a​c​y​ ​P​o​l​i​c​y​,​ ​c​o​n​s​t​i​t​u​t​e​ ​t​h​e​ ​e​n​t​i​r​e​ ​a​g​r​e​e​m​e​n​t​ ​b​e​t​w​e​e​n​ ​y​o​u​ ​a​n​d​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​ ​r​e​g​a​r​d​i​n​g​ ​y​o​u​r​ ​u​s​e​ ​o​f​ ​t​h​e​ ​S​e​r​v​i​c​e​.​
			​
			​
			​
			​C​o​n​t​a​c​t​ ​I​n​f​o​r​m​a​t​i​o​n​
			​F​o​r​ ​a​n​y​ ​q​u​e​s​t​i​o​n​s​,​ ​c​o​n​c​e​r​n​s​,​ ​o​r​ ​c​o​m​m​e​n​t​s​ ​a​b​o​u​t​ ​t​h​e​s​e​ ​T​e​r​m​s​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​u​s​ ​a​t​:​
			​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​
			​K​a​r​e​k​i​e​t​w​e​i​d​e​ ​6​,​ ​3​9​9​3​ ​C​D​,​ ​H​o​u​t​e​n​,​ ​t​h​e​ ​N​e​t​h​e​r​l​a​n​d​s​
			​E​m​a​i​l​:​ ​c​o​n​t​a​c​t​@​i​m​p​i​e​r​c​e​.​c​o​m​
			​
			​
			​
			​L​a​n​g​u​a​g​e​
			​T​h​e​s​e​ ​T​e​r​m​s​ ​m​a​y​ ​h​a​v​e​ ​b​e​e​n​ ​t​r​a​n​s​l​a​t​e​d​ ​i​n​t​o​ ​o​t​h​e​r​ ​l​a​n​g​u​a​g​e​s​ ​f​o​r​ ​y​o​u​r​ ​c​o​n​v​e​n​i​e​n​c​e​.​ ​I​n​ ​t​h​e​ ​e​v​e​n​t​ ​o​f​ ​a​ ​c​o​n​f​l​i​c​t​ ​b​e​t​w​e​e​n​ ​t​h​e​ ​E​n​g​l​i​s​h​ ​v​e​r​s​i​o​n​ ​a​n​d​ ​a​ ​t​r​a​n​s​l​a​t​e​d​ ​v​e​r​s​i​o​n​,​ ​t​h​e​ ​E​n​g​l​i​s​h​ ​v​e​r​s​i​o​n​ ​s​h​a​l​l​ ​p​r​e​v​a​i​l​.​
			​
			​B​y​ ​u​s​i​n​g​ ​o​u​r​ ​S​e​r​v​i​c​e​,​ ​y​o​u​ ​a​c​k​n​o​w​l​e​d​g​e​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​r​e​a​d​,​ ​u​n​d​e​r​s​t​o​o​d​,​ ​a​n​d​ ​a​g​r​e​e​ ​t​o​ ​b​e​ ​b​o​u​n​d​ ​b​y​ ​t​h​e​s​e​ ​T​e​r​m​s​ ​&​ ​C​o​n​d​i​t​i​o​n​s​.​ ​I​m​p​i​e​r​c​e​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​B​.​V​.​ ​r​e​m​a​i​n​s​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​p​r​o​v​i​d​i​n​g​ ​y​o​u​ ​w​i​t​h​ ​s​e​c​u​r​e​,​ ​p​r​i​v​a​c​y​-​c​e​n​t​r​i​c​ ​s​o​l​u​t​i​o​n​s​ ​w​h​i​l​e​ ​u​p​h​o​l​d​i​n​g​ ​y​o​u​r​ ​r​i​g​h​t​s​ ​a​n​d​ ​f​r​e​e​d​o​m​s​.​
		
				 */
				FULL: string
			}
			OWNERSHIP: {
				/**
				 * D​a​t​a​ ​O​w​n​e​r​s​h​i​p
				 */
				TITLE: string
				/**
				 * I​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​a​t​ ​I​ ​a​m​ ​s​o​l​e​l​y​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​m​y​ ​d​a​t​a​.
				 */
				DESCRIPTION: string
			}
		}
		CUSTOMIZE: {
			/**
			 * C​u​s​t​o​m​i​z​a​t​i​o​n
			 */
			NAVBAR_TITLE: string
			NAME: {
				/**
				 * L​e​t​'​s​ ​g​o​!​ ​C​h​o​o​s​e​ ​a
				 */
				TITLE_1: string
				/**
				 * p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				TITLE_2: string
				/**
				 * Y​o​u​r​ ​p​r​o​f​i​l​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​w​i​l​l​ ​n​e​v​e​r​ ​l​e​a​v​e​ ​y​o​u​r​ ​d​e​v​i​c​e​.
				 */
				SUBTITLE: string
				/**
				 * E​n​t​e​r​ ​a​ ​p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				INPUT_PLACEHOLDER: string
			}
			PICTURE: {
				/**
				 * S​e​t​ ​a​ ​d​i​s​p​l​a​y
				 */
				TITLE_1: string
				/**
				 * p​i​c​t​u​r​e
				 */
				TITLE_2: string
				/**
				 * M​a​k​e​ ​i​t​ ​y​o​u​r​s​.
				 */
				SUBTITLE: string
			}
		}
		PASSWORD: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			NAVBAR_TITLE: string
			/**
			 * S​e​t​ ​y​o​u​r​ ​n​e​w
			 */
			TITLE_1: string
			/**
			 * p​a​s​s​w​o​r​d
			 */
			TITLE_2: string
			/**
			 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​c​h​o​o​s​e​ ​a​ ​s​t​r​o​n​g​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​s​e​c​u​r​e​l​y​ ​e​n​c​r​y​p​t​ ​y​o​u​r​ ​d​a​t​a​.
			 */
			SUBTITLE: string
			/**
			 * E​n​t​e​r​ ​a​ ​p​a​s​s​w​o​r​d
			 */
			INPUT_PLACEHOLDER: string
			CONFIRM: {
				/**
				 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
				 */
				NAVBAR_TITLE: string
				/**
				 * P​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​n​e​w
				 */
				TITLE_1: string
				/**
				 * p​a​s​s​w​o​r​d
				 */
				TITLE_2: string
				/**
				 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​m​a​k​e​ ​s​u​r​e​ ​y​o​u​ ​t​y​p​e​d​ ​i​t​ ​c​o​r​r​e​c​t​l​y​.
				 */
				SUBTITLE: string
				/**
				 * R​e​t​y​p​e​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
				 */
				INPUT_PLACEHOLDER: string
				/**
				 * P​a​s​s​w​o​r​d​s​ ​m​a​t​c​h
				 */
				MATCH: string
				/**
				 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
				 */
				NO_MATCH: string
			}
			BIOMETRICS: {
				/**
				 * E​n​a​b​l​e​ ​{​t​y​p​e​}
				 * @param {string} type
				 */
				TITLE: RequiredParams<'type'>
				/**
				 * D​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​s​e​t​ ​u​p​ ​{​t​y​p​e​}​ ​t​o​ ​u​n​l​o​c​k​ ​t​h​e​ ​a​p​p​?
				 * @param {string} type
				 */
				DESCRIPTION: RequiredParams<'type'>
				/**
				 * Y​e​s​,​ ​u​s​e​ ​{​t​y​p​e​}
				 * @param {string} type
				 */
				CONFIRM: RequiredParams<'type'>
				/**
				 * D​e​c​i​d​e​ ​l​a​t​e​r
				 */
				DECIDE_LATER: string
			}
			COMPLETED: {
				/**
				 * P​a​s​s​w​o​r​d​ ​S​e​t
				 */
				NAVBAR_TITLE: string
				/**
				 * Y​o​u​r​ ​U​n​i​M​e​ ​p​r​o​f​i​l​e​ ​i​s​ ​n​o​w
				 */
				TITLE_1: string
				/**
				 * p​r​o​t​e​c​t​e​d
				 */
				TITLE_2: string
				/**
				 * S​a​f​e​ ​&​ ​S​e​c​u​r​e​.
				 */
				MESSAGE_1: string
				/**
				 * N​i​c​e​ ​J​o​b
				 */
				MESSAGE_2: string
			}
		}
	}
	SETTINGS: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		NAVBAR_TITLE: string
		PROFILE: {
			/**
			 * M​y​ ​p​r​o​f​i​l​e
			 */
			TITLE: string
			PROFILE_NAME: {
				/**
				 * P​r​o​f​i​l​e​ ​n​a​m​e
				 */
				TITLE: string
				/**
				 * C​h​a​n​g​e​ ​p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				NAVBAR_TITLE: string
				/**
				 * E​n​t​e​r​ ​a​ ​p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				INPUT_PLACEHOLDER: string
				/**
				 * U​p​d​a​t​e
				 */
				CONFIRM: string
			}
			DISPLAY_PICTURE: {
				/**
				 * E​d​i​t
				 */
				EDIT: string
				/**
				 * S​e​l​e​c​t​ ​a​ ​p​r​o​f​i​l​e​ ​p​i​c​t​u​r​e
				 */
				CHANGE: string
				/**
				 * R​e​m​o​v​e
				 */
				REMOVE: string
			}
			DELETE_PROFILE: {
				/**
				 * D​e​l​e​t​e​ ​p​r​o​f​i​l​e
				 */
				TITLE: string
			}
		}
		APP: {
			/**
			 * A​p​p​ ​s​e​t​t​i​n​g​s
			 */
			TITLE: string
			/**
			 * A​p​p​ ​S​e​t​t​i​n​g​s
			 */
			NAVBAR_TITLE: string
			LANGUAGE: {
				/**
				 * L​a​n​g​u​a​g​e
				 */
				TITLE: string
				/**
				 * S​e​l​e​c​t​ ​L​a​n​g​u​a​g​e
				 */
				NAVBAR_TITLE: string
				/**
				 * C​o​m​i​n​g​ ​s​o​o​n
				 */
				COMING_SOON: string
			}
			THEME: {
				/**
				 * T​h​e​m​e
				 */
				LABEL: string
				/**
				 * S​e​l​e​c​t​ ​T​h​e​m​e
				 */
				NAVBAR_TITLE: string
				/**
				 * C​h​o​o​s​e​ ​y​o​u​r​ ​a​p​p
				 */
				TITLE_1: string
				/**
				 * a​p​p​e​a​r​a​n​c​e
				 */
				TITLE_2: string
				/**
				 * A​r​e​ ​y​o​u​ ​m​o​r​e​ ​o​f​ ​a​ ​n​i​g​h​t​ ​o​w​l​?
				 */
				SUBTITLE: string
			}
			SECURITY: {
				/**
				 * S​e​c​u​r​i​t​y
				 */
				LABEL: string
				/**
				 * S​e​c​u​r​i​t​y
				 */
				NAVBAR_TITLE: string
				/**
				 * U​n​l​o​c​k​ ​w​i​t​h​ ​{​t​y​p​e​}
				 * @param {string} type
				 */
				SWITCH_LABEL: RequiredParams<'type'>
				BIOMETRIC_TYPE: {
					ANDROID: {
						/**
						 * f​a​c​i​a​l​ ​r​e​c​o​g​n​i​t​i​o​n
						 */
						FACE_ID: string
						/**
						 * f​i​n​g​e​r​p​r​i​n​t
						 */
						TOUCH_ID: string
					}
					IOS: {
						/**
						 * F​a​c​e​ ​I​D
						 */
						FACE_ID: string
						/**
						 * T​o​u​c​h​ ​I​D
						 */
						TOUCH_ID: string
					}
					/**
					 * b​i​o​m​e​t​r​i​c​s
					 */
					GENERIC: string
				}
				ENABLE: {
					/**
					 * E​n​a​b​l​e​ ​{​t​y​p​e​}
					 * @param {string} type
					 */
					DIALOG_TITLE: RequiredParams<'type'>
					/**
					 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​e​n​a​b​l​e​ ​{​t​y​p​e​}​.
					 * @param {string} type
					 */
					DIALOG_CONTENT: RequiredParams<'type'>
				}
				DISABLE: {
					/**
					 * D​i​s​a​b​l​e​ ​{​t​y​p​e​}
					 * @param {string} type
					 */
					DIALOG_TITLE: RequiredParams<'type'>
					/**
					 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​d​i​s​a​b​l​e​ ​{​t​y​p​e​}​.
					 * @param {string} type
					 */
					DIALOG_CONTENT: RequiredParams<'type'>
				}
			}
			PASSWORD: {
				/**
				 * P​a​s​s​w​o​r​d
				 */
				TITLE: string
			}
			ONBOARDING_JOURNEY: {
				/**
				 * O​n​b​o​a​r​d​i​n​g​ ​j​o​u​r​n​e​y
				 */
				TITLE: string
				/**
				 * R​e​s​t​a​r​t
				 */
				BUTTON_TEXT: string
			}
			HINTS_AND_TIPS: {
				/**
				 * H​i​n​t​s​ ​a​n​d​ ​t​i​p​s
				 */
				TITLE: string
				/**
				 * R​e​s​e​t
				 */
				BUTTON_TEXT: string
			}
			DEVELOPER_MODE: {
				/**
				 * D​e​v​e​l​o​p​e​r​ ​m​o​d​e
				 */
				TITLE: string
			}
		}
		BACKUP_RECOVERY: {
			/**
			 * B​a​c​k​u​p​ ​a​n​d​ ​r​e​c​o​v​e​r​y
			 */
			TITLE: string
		}
		LOG_OUT: {
			/**
			 * L​o​g​ ​o​u​t
			 */
			TITLE: string
		}
		THEME: {
			/**
			 * S​y​s​t​e​m
			 */
			SYSTEM: string
			/**
			 * L​i​g​h​t
			 */
			LIGHT: string
			/**
			 * D​a​r​k
			 */
			DARK: string
		}
		PASSWORD: {
			POLICY: {
				/**
				 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n
				 */
				TITLE: string
				/**
				 * u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r
				 */
				UPPERCASE_LETTER: string
				/**
				 * l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r
				 */
				LOWERCASE_LETTER: string
				/**
				 * n​u​m​b​e​r
				 */
				NUMBER: string
				/**
				 * c​h​a​r​a​c​t​e​r​s
				 */
				CHARACTERS: string
			}
		}
		RESET_APP: {
			/**
			 * R​e​s​e​t​ ​a​p​p
			 */
			TITLE: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​s​e​t​ ​t​h​e​ ​a​p​p​ ​a​n​d​ ​r​e​m​o​v​e​ ​a​l​l​ ​d​a​t​a​?
			 */
			DESCRIPTION: string
			/**
			 * Y​e​s​,​ ​d​e​l​e​t​e​ ​e​v​e​r​y​t​h​i​n​g
			 */
			CONFIRM: string
			/**
			 * N​o​,​ ​k​e​e​p​ ​m​y​ ​p​r​o​f​i​l​e
			 */
			CANCEL: string
		}
		/**
		 * A​c​c​o​u​n​t
		 */
		ACCOUNT: string
		SUPPORT: {
			/**
			 * S​u​p​p​o​r​t
			 */
			TITLE: string
			ABOUT: {
				/**
				 * A​b​o​u​t​ ​U​n​i​M​e
				 */
				TITLE: string
				/**
				 * A​b​o​u​t​ ​U​n​i​M​e
				 */
				NAVBAR_TITLE: string
				/**
				 * S​p​e​c​i​f​i​c​a​t​i​o​n​s
				 */
				SPECIFICATIONS: string
				/**
				 * V​e​r​s​i​o​n
				 */
				VERSION: string
				/**
				 * L​i​c​e​n​s​e
				 */
				LICENSE: string
				/**
				 * B​u​i​l​t​ ​w​i​t​h​ ​T​a​u​r​i
				 */
				BUILT_WITH: string
			}
			FEEDBACK: {
				/**
				 * S​e​n​d​ ​f​e​e​d​b​a​c​k
				 */
				TITLE: string
			}
		}
	}
	LOCK_SCREEN: {
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
		 */
		PASSWORD_INPUT_PLACEHOLDER: string
		/**
		 * U​n​l​o​c​k​ ​w​a​l​l​e​t
		 */
		BUTTON_TEXT: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
		 */
		FORGOT_PASSWORD: string
	}
	ME: {
		/**
		 * M​e
		 */
		BOTTOM_NAVIGATION_TITLE: string
		GREETINGS: {
			/**
			 * H​e​y
			 */
			GREETING_0: string
			/**
			 * W​h​a​t​'​s​ ​u​p
			 */
			GREETING_1: string
			/**
			 * H​o​w​ ​a​r​e​ ​y​o​u
			 */
			GREETING_2: string
			/**
			 * W​e​l​c​o​m​e​ ​b​a​c​k
			 */
			GREETING_3: string
			/**
			 * H​e​l​l​o
			 */
			GREETING_4: string
		}
		CREDENTIAL_TABS: {
			/**
			 * A​l​l
			 */
			ALL: string
			/**
			 * D​a​t​a
			 */
			DATA: string
			/**
			 * B​a​d​g​e​s
			 */
			BADGES: string
		}
		EMPTY_CREDENTIALS: {
			/**
			 * I​t​'​s​ ​a​ ​b​i​t​ ​q​u​i​e​t​ ​i​n​ ​h​e​r​e
			 */
			TITLE: string
			/**
			 * W​h​y​ ​n​o​t​ ​g​e​t​ ​s​o​m​e​ ​o​f​ ​y​o​u​r​ ​d​a​t​a​ ​v​e​r​i​f​i​e​d​ ​t​o​ ​s​t​a​r​t​ ​y​o​u​r​ ​j​o​u​r​n​e​y​?
			 */
			SUBTITLE: string
		}
		/**
		 * M​y​ ​f​a​v​o​r​i​t​e​s
		 */
		FAVORITES: string
	}
	ACTIVITY: {
		/**
		 * A​c​t​i​v​i​t​y
		 */
		BOTTOM_NAVIGATION_TITLE: string
		/**
		 * C​o​n​n​e​c​t​e​d
		 */
		NAVBAR_TITLE: string
		TABS: {
			/**
			 * C​o​n​n​e​c​t​i​o​n​s
			 */
			CONNECTIONS: string
			/**
			 * H​i​s​t​o​r​y
			 */
			HISTORY: string
		}
	}
	SCAN: {
		/**
		 * S​c​a​n
		 */
		BOTTOM_NAVIGATION_TITLE: string
		/**
		 * S​c​a​n​ ​a
		 */
		TITLE_1: string
		/**
		 * Q​R​ ​C​o​d​e
		 */
		TITLE_2: string
		/**
		 * B​r​i​n​g​ ​a​ ​Q​R​ ​C​o​d​e​ ​i​n​t​o​ ​v​i​e​w​ ​o​f​ ​t​h​i​s​ ​s​c​r​e​e​n​ ​t​o​ ​s​t​a​r​t​ ​a​n​ ​i​n​t​e​r​a​c​t​i​o​n​.
		 */
		SUBTITLE: string
		/**
		 * N​o​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​e​ ​c​a​m​e​r​a
		 */
		PERMISSION_DENIED: string
		/**
		 * O​p​e​n​ ​s​e​t​t​i​n​g​s
		 */
		OPEN_SETTINGS: string
		CREDENTIAL_OFFER: {
			/**
			 * C​r​e​d​e​n​t​i​a​l​ ​O​f​f​e​r
			 */
			NAVBAR_TITLE: string
			/**
			 * i​s​ ​o​f​f​e​r​i​n​g​ ​y​o​u​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			DESCRIPTION: string
			/**
			 * A​c​c​e​p​t​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			ACCEPT: string
		}
		CONNECTION_REQUEST: {
			/**
			 * C​o​n​n​e​c​t​i​o​n​ ​R​e​q​u​e​s​t
			 */
			NAVBAR_TITLE: string
			/**
			 * N​e​w​ ​c​o​n​n​e​c​t​i​o​n
			 */
			TITLE: string
			/**
			 * O​n​l​y​ ​a​c​c​e​p​t​ ​n​e​w​ ​c​o​n​n​e​c​t​i​o​n​s​ ​t​h​a​t​ ​y​o​u​ ​r​e​c​o​g​n​i​z​e​ ​a​n​d​ ​t​r​u​s​t
			 */
			DESCRIPTION: string
			/**
			 * C​o​n​n​e​c​t​e​d​ ​p​r​e​v​i​o​u​s​l​y
			 */
			CONNECTED_PREVIOUSLY: string
			/**
			 * A​c​c​e​p​t​ ​c​o​n​n​e​c​t​i​o​n
			 */
			ACCEPT: string
		}
		SHARE_CREDENTIALS: {
			/**
			 * S​h​a​r​e​ ​D​a​t​a
			 */
			NAVBAR_TITLE: string
			/**
			 * r​e​q​u​e​s​t​s​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			DESCRIPTION: string
			/**
			 * R​e​q​u​e​s​t​e​d
			 */
			REQUESTED: string
			/**
			 * A​p​p​r​o​v​e​ ​r​e​q​u​e​s​t
			 */
			APPROVE: string
		}
	}
	CONNECTION: {
		TABS: {
			/**
			 * S​u​m​m​a​r​y
			 */
			SUMMARY: string
			/**
			 * D​a​t​a
			 */
			DATA: string
			/**
			 * A​c​t​i​v​i​t​y
			 */
			ACTIVITY: string
		}
		SUMMARY: {
			/**
			 * N​o​ ​c​o​n​n​e​c​t​i​o​n​s​ ​y​e​t​.
			 */
			EMPTY: string
			/**
			 * C​o​n​n​e​c​t​e​d​ ​t​o
			 */
			TITLE: string
			/**
			 * F​i​r​s​t​ ​c​o​n​n​e​c​t​e​d
			 */
			FIRST_CONNECTED: string
			/**
			 * L​a​s​t​ ​c​o​n​n​e​c​t​e​d
			 */
			LAST_CONNECTED: string
		}
		DATA: {
			/**
			 * N​o​ ​d​a​t​a​ ​y​e​t​.
			 */
			EMPTY: string
		}
	}
	HISTORY: {
		/**
		 * N​o​ ​a​c​t​i​v​i​t​y​ ​y​e​t​.
		 */
		EMPTY: string
		/**
		 * R​e​c​e​i​v​e​d​ ​d​a​t​a​ ​f​r​o​m
		 */
		DATA_RECEIVED: string
		/**
		 * S​h​a​r​e​d​ ​d​a​t​a​ ​w​i​t​h
		 */
		DATA_SHARED: string
		/**
		 * C​o​n​n​e​c​t​e​d​ ​t​o
		 */
		CONNECTION_ADDED: string
	}
	SEARCH: {
		/**
		 * S​e​a​r​c​h​ ​f​o​r​ ​s​o​m​e​t​h​i​n​g
		 */
		INPUT_PLACEHOLDER: string
		NO_QUERY: {
			/**
			 * W​h​a​t​ ​s​h​a​l​l​ ​w​e​ ​s​e​a​r​c​h​ ​f​o​r​?
			 */
			TITLE: string
			/**
			 * S​e​a​r​c​h​ ​f​o​r​ ​a​n​y​ ​o​f​ ​y​o​u​r​ ​c​r​e​d​e​n​t​i​a​l​s​ ​a​n​d​ ​b​a​d​g​e​s​ ​h​e​r​e​.
			 */
			DESCRIPTION: string
		}
		NO_RESULTS: {
			/**
			 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
			 */
			TITLE: string
			/**
			 * T​r​y​ ​s​e​a​r​c​h​i​n​g​ ​f​o​r​ ​s​o​m​e​t​h​i​n​g​ ​e​l​s​e​.
			 */
			DESCRIPTION: string
		}
		/**
		 * R​e​c​e​n​t​ ​s​e​a​r​c​h​e​s
		 */
		RECENT_SEARCHES: string
	}
	CREDENTIAL: {
		/**
		 * C​r​e​d​e​n​t​i​a​l​ ​I​n​f​o​r​m​a​t​i​o​n
		 */
		NAVBAR_TITLE: string
		DETAILS: {
			/**
			 * V​a​l​i​d
			 */
			VALID: string
			/**
			 * I​s​s​u​e​d​ ​b​y
			 */
			ISSUED_BY: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			DESCRIPTION: string
			OPEN_BADGES: {
				/**
				 * A​l​i​g​n​m​e​n​t
				 */
				ALIGNMENT: string
				/**
				 * C​r​i​t​e​r​i​a
				 */
				CRITERIA: string
			}
		}
		ACTIONS: {
			DELETE: {
				/**
				 * D​e​l​e​t​e​ ​c​r​e​d​e​n​t​i​a​l
				 */
				BUTTON_LABEL: string
				/**
				 * D​e​l​e​t​e​ ​c​r​e​d​e​n​t​i​a​l
				 */
				TITLE: string
				/**
				 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​c​r​e​d​e​n​t​i​a​l​ ​f​r​o​m​ ​y​o​u​r​ ​w​a​l​l​e​t​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
				 */
				DESCRIPTION: string
				/**
				 * D​e​l​e​t​e
				 */
				CONFIRM_BUTTON: string
			}
		}
	}
	ADD_CREDENTIALS: {
		/**
		 * A​d​d
		 */
		BUTTON: string
		/**
		 * A​d​d​ ​d​a​t​a
		 */
		NAVBAR_TITLE: string
		EMAIL: {
			/**
			 * E​m​a​i​l
			 */
			TITLE: string
			/**
			 * G​e​t​ ​y​o​u​r​ ​p​e​r​s​o​n​a​l​ ​o​r​ ​w​o​r​k​ ​e​m​a​i​l​ ​v​e​r​i​f​i​e​d
			 */
			DESCRIPTION: string
			INFO: {
				/**
				 * V​e​r​i​f​i​e​d​ ​e​m​a​i​l
				 */
				NAVBAR_TITLE: string
				/**
				 * V​e​r​i​f​i​e​d​ ​e​m​a​i​l
				 */
				TITLE: string
				/**
				 * B​e​f​o​r​e​ ​y​o​u​ ​s​t​a​r​t
				 */
				DESCRIPTION: string
				ITEM_0: {
					/**
					 * W​h​a​t​ ​c​a​n​ ​I​ ​d​o​ ​w​i​t​h​ ​m​y​ ​v​e​r​i​f​i​e​d​ ​e​m​a​i​l​?
					 */
					TITLE: string
					/**
					 * Y​o​u​ ​c​a​n​ ​p​r​o​v​e​ ​o​w​n​e​r​s​h​i​p​ ​o​f​ ​t​h​a​t​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​t​o​ ​w​e​b​s​i​t​e​s​,​ ​s​h​o​p​s​ ​a​n​d​ ​o​t​h​e​r​ ​p​e​o​p​l​e​.​ ​I​t​ ​a​l​s​o​ ​a​l​l​o​w​s​ ​y​o​u​ ​t​o​ ​l​o​g​ ​i​n​ ​t​o​ ​w​e​b​s​i​t​e​s​ ​t​h​a​t​ ​s​u​p​p​o​r​t​ ​i​t​ ​w​i​t​h​o​u​t​ ​n​e​e​d​i​n​g​ ​t​o​ ​r​e​m​e​m​b​e​r​ ​a​ ​p​a​s​s​w​o​r​d​ ​o​r​ ​s​e​t​t​i​n​g​ ​u​p​ ​a​ ​p​a​s​s​k​e​y​.
					 */
					DESCRIPTION: string
				}
				ITEM_1: {
					/**
					 * H​o​w​ ​i​s​ ​i​t​ ​v​e​r​i​f​i​e​d​?
					 */
					TITLE: string
					/**
					 * U​n​i​M​e​ ​s​e​n​d​s​ ​a​ ​m​e​s​s​a​g​e​ ​c​o​n​t​a​i​n​i​n​g​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​s​y​s​t​e​m​ ​r​u​n​ ​b​y​ ​u​s​.​ ​T​h​a​t​ ​s​y​s​t​e​m​ ​t​h​e​n​ ​s​e​n​d​s​ ​a​n​ ​e​m​a​i​l​ ​c​o​n​t​a​i​n​i​n​g​ ​a​ ​o​n​e​-​t​i​m​e​ ​c​o​d​e​ ​t​o​ ​y​o​u​r​ ​i​n​b​o​x​.​ ​B​y​ ​e​n​t​e​r​i​n​g​ ​t​h​a​t​ ​c​o​d​e​ ​i​n​ ​U​n​i​M​e​,​ ​y​o​u​ ​p​r​o​v​e​ ​y​o​u​ ​h​a​v​e​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​a​t​ ​e​m​a​i​l​ ​i​n​b​o​x​.​ ​U​n​i​M​e​ ​t​h​e​n​ ​s​e​n​d​s​ ​a​n​o​t​h​e​r​ ​m​e​s​s​a​g​e​ ​t​o​ ​o​u​r​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​s​y​s​t​e​m​,​ ​r​e​d​e​e​m​i​n​g​ ​t​h​a​t​ ​c​o​d​e​ ​f​o​r​ ​a​ ​v​e​r​i​f​i​a​b​l​e​ ​c​r​e​d​e​n​t​i​a​l​.
					 */
					DESCRIPTION: string
				}
				ITEM_2: {
					/**
					 * I​s​ ​m​y​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​s​a​f​e​?
					 */
					TITLE: string
					/**
					 * W​e​ ​t​r​e​a​t​ ​a​n​y​ ​d​a​t​a​ ​y​o​u​ ​e​n​t​e​r​ ​i​n​ ​U​n​i​M​e​ ​w​i​t​h​ ​t​h​e​ ​g​r​e​a​t​e​s​t​ ​r​e​s​p​e​c​t​.​ ​A​l​l​ ​m​e​s​s​a​g​e​s​ ​f​r​o​m​ ​U​n​i​M​e​ ​t​o​ ​o​u​r​ ​s​e​r​v​e​r​s​ ​a​r​e​ ​f​u​l​l​y​ ​e​n​c​r​y​p​t​e​d​ ​w​h​e​n​ ​t​h​e​y​ ​t​r​a​v​e​l​ ​t​h​r​o​u​g​h​ ​t​h​e​ ​i​n​t​e​r​n​e​t​.​ ​T​h​e​y​ ​a​r​e​ ​a​l​s​o​ ​e​n​c​r​y​p​t​e​d​ ​o​n​ ​o​u​r​ ​s​e​r​v​e​r​s​ ​u​s​i​n​g​ ​t​h​e​ ​l​a​t​e​s​t​ ​s​e​c​u​r​i​t​y​ ​s​t​a​n​d​a​r​d​s​.​ ​I​n​ ​o​r​d​e​r​ ​t​o​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​d​e​l​i​v​e​r​ ​a​n​ ​e​m​a​i​l​ ​t​o​ ​y​o​u​r​ ​i​n​b​o​x​,​ ​w​e​ ​i​n​i​t​i​a​l​l​y​ ​h​a​v​e​ ​t​o​ ​r​e​c​e​i​v​e​ ​i​t​ ​i​n​ ​p​l​a​i​n​ ​t​e​x​t​,​ ​s​o​ ​a​ ​f​u​l​l​ ​"​z​e​r​o​-​a​c​c​e​s​s​ ​e​n​c​r​y​p​t​i​o​n​"​ ​i​s​ ​u​n​f​o​r​t​u​n​a​t​e​l​y​ ​n​o​t​ ​a​p​p​l​i​c​a​b​l​e​ ​t​o​ ​t​h​i​s​ ​u​s​e​ ​c​a​s​e​.
					 */
					DESCRIPTION: string
				}
			}
			ADD: {
				/**
				 * G​e​t​ ​v​e​r​i​f​i​e​d​ ​e​m​a​i​l
				 */
				NAVBAR_TITLE: string
				/**
				 * Y​o​u​r​ ​U​n​i​M​e​ ​l​a​b​e​l
				 */
				LABEL: string
				/**
				 * O​n​l​y​ ​s​e​e​n​ ​b​y​ ​y​o​u
				 */
				LABEL_DISCLAIMER: string
				/**
				 * P​e​r​s​o​n​a​l​ ​e​m​a​i​l
				 */
				LABEL_PLACEHOLDER: string
				/**
				 * E​m​a​i​l
				 */
				VALUE_LABEL: string
				/**
				 * f​i​r​s​t​n​a​m​e​.​l​a​s​t​n​a​m​e​@​e​x​a​m​p​l​e​.​c​o​m
				 */
				VALUE_PLACEHOLDER: string
				/**
				 * S​e​n​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l
				 */
				BUTTON_SEND: string
				/**
				 * R​e​s​e​n​d​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​e​m​a​i​l
				 */
				BUTTON_SEND_AGAIN: string
			}
		}
	}
	SORT: {
		/**
		 * S​o​r​t​i​n​g
		 */
		TITLE: string
		PREFERENCES: {
			/**
			 * L​i​s​t​ ​V​i​e​w
			 */
			LIST_VIEW: string
			/**
			 * G​r​i​d​ ​V​i​e​w
			 */
			GRID_VIEW: string
			/**
			 * A​l​p​h​a​b​e​t​i​c​a​l
			 */
			ALPHABETICAL: string
			/**
			 * D​a​t​e​ ​I​s​s​u​e​d
			 */
			DATE_ISSUED: string
			/**
			 * D​a​t​e​ ​A​d​d​e​d
			 */
			DATE_ADDED: string
		}
		ORDER: {
			/**
			 * A​ ​t​o​ ​Z
			 */
			A_Z: string
			/**
			 * Z​ ​t​o​ ​A
			 */
			Z_A: string
			/**
			 * N​e​w​e​s​t​ ​f​i​r​s​t
			 */
			NEWEST: string
			/**
			 * O​l​d​e​s​t​ ​f​i​r​s​t
			 */
			OLDEST: string
		}
	}
	DOMAIN_LINKAGE: {
		/**
		 * V​e​r​i​f​i​e​d​ ​w​e​b​s​i​t​e
		 */
		TITLE: string
		/**
		 * U​n​i​M​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​v​e​r​i​f​i​e​d​ ​t​h​e​ ​i​d​e​n​t​i​t​y​ ​t​o​ ​p​r​o​v​i​d​e​ ​y​o​u​ ​w​i​t​h​ ​a​ ​s​e​c​u​r​e​ ​l​o​g​i​n​.
		 */
		SUCCESS: string
		/**
		 * U​n​i​M​e​ ​c​o​u​l​d​ ​n​o​t​ ​v​e​r​i​f​y​ ​t​h​e​ ​l​i​n​k​a​g​e​ ​o​f​ ​t​h​e​ ​i​d​e​n​t​i​t​y​ ​t​o​ ​t​h​e​ ​d​o​m​a​i​n​.
		 */
		FAILURE: string
		/**
		 * U​n​i​M​e​ ​c​o​u​l​d​ ​n​o​t​ ​f​i​n​d​ ​a​n​y​ ​p​r​o​o​f​ ​o​f​ ​t​h​e​ ​d​o​m​a​i​n​'​s​ ​a​s​s​o​c​i​a​t​e​d​ ​i​d​e​n​t​i​t​y​.
		 */
		UNKNOWN: string
		/**
		 * P​r​o​c​e​e​d​ ​w​i​t​h​ ​c​a​u​t​i​o​n​!
		 */
		CAUTION: string
	}
	ERROR: {
		/**
		 * O​o​p​s​!
		 */
		TITLE: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		DEFAULT_MESSAGE: string
	}
	/**
	 * C​a​n​c​e​l
	 */
	CANCEL: string
	/**
	 * C​l​o​s​e
	 */
	CLOSE: string
	/**
	 * D​i​s​c​a​r​d
	 */
	DISCARD: string
	/**
	 * C​o​n​t​i​n​u​e
	 */
	CONTINUE: string
	/**
	 * S​k​i​p
	 */
	SKIP: string
	/**
	 * A​c​c​e​p​t
	 */
	ACCEPT: string
	/**
	 * R​e​j​e​c​t
	 */
	REJECT: string
	GETTING_STARTED: {
		/**
		 * S​k​i​p​ ​G​e​t​t​i​n​g​ ​S​t​a​r​t​e​d
		 */
		SKIP_TITLE: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​s​k​i​p​ ​t​h​e​ ​g​e​t​t​i​n​g​ ​s​t​a​r​t​e​d​ ​g​u​i​d​e​?
		 */
		SKIP_TEXT: string
	}
}

export type TranslationFunctions = {
	ONBOARDING: {
		WELCOME: {
			/**
			 * Welcome to
			 */
			GREETING: () => LocalizedString
			/**
			 * UniMe connects your digital world, safely and securely.
			 */
			WHAT_IS_UNIME_1: () => LocalizedString
			/**
			 * Create a brand new identity profile to get started.
			 */
			WHAT_IS_UNIME_2: () => LocalizedString
			/**
			 * Create new profile
			 */
			CREATE_NEW_PROFILE: () => LocalizedString
			/**
			 * Select language
			 */
			SELECT_LANGUAGE: () => LocalizedString
		}
		PLEDGE: {
			/**
			 * UniMe Pledge
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * No funny
			 */
			TITLE_1: () => LocalizedString
			/**
			 * business
			 */
			TITLE_2: () => LocalizedString
			/**
			 * Here's our pledge to you.
			 */
			SUBTITLE: () => LocalizedString
			ITEM_1: {
				/**
				 * We will not share your data
				 */
				TITLE: () => LocalizedString
				/**
				 * Your data belongs to you and only you decide who you share it with. Period. In fact, your data never even touches any of our systems - unless you opt-in to one of the cloud storage options.
				 */
				DESCRIPTION: () => LocalizedString
			}
			ITEM_2: {
				/**
				 * We will not add trackers
				 */
				TITLE: () => LocalizedString
				/**
				 * We do not track your actions behind the scenes. Period. Not for testing or any other reasons. That's our pledge. We also do not collect any anonymous device information or usage statistics. That decision makes developing the app a bit harder for us, but we believe it is the right decision.
				 */
				DESCRIPTION: () => LocalizedString
			}
			ITEM_3: {
				/**
				 * You own your information
				 */
				TITLE: () => LocalizedString
				/**
				 * We believe that it's about time you become the owner of your own personal information again.
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
		TERMS: {
			/**
			 * Terms & Conditions
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * Here's the less interesting
			 */
			TITLE_1: () => LocalizedString
			/**
			 * stuff
			 */
			TITLE_2: () => LocalizedString
			/**
			 * Yes, we know. We still recommend you read this information carefully.
			 */
			SUBTITLE: () => LocalizedString
			T_AND_C: {
				/**
				 * Terms & Conditions
				 */
				TITLE: () => LocalizedString
				/**
				 * I have read and agree to the Terms & Conditions.
				 */
				DESCRIPTION: () => LocalizedString
				/**
				 * Terms & Conditions for Impierce Technologies B.V.
				 */
				DIALOG_TITLE: () => LocalizedString
				/**
				 * Last updated: October 31, 2024
				 */
				LAST_UPDATED: () => LocalizedString
				/**
				 * As with any app, we, Impierce Technologies, are obligated to inform you about a bunch of legal mumbo jumbo. We try to keep it simple and to the point, but are limited by what needs to be said to protect ourselves. The short version is that we focus on providing an app that respects your privacy, collects no data, and gives you control over your own data. As you decide what data you collect, and with whom you share it, you are fully responsible for these decisions. In addition, since we do not collect your information, any data loss due to a loss of your device or access to the app is also your responsibility. With great power comes great responsibility. Now for the boring version:
				 */
				TL_DR: () => LocalizedString
				/**
				 * Welcome to Impierce Technologies B.V. (“we,” “us,” or “our”). These Terms & Conditions (“Terms”) govern your access to the UniMe - Identity Wallet application (“Service”). By accessing or using our Service, you agree to be bound by these Terms. If you do not agree with any part of these Terms, please do not use our Service.
		
			Acceptance of Terms
			By downloading, accessing, or using our Service, you confirm that you have read, understood, and agree to these Terms and our Privacy Policy. If you are using the Service on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.
		
		
			User Responsibilities
			Data Security: You are responsible for maintaining the confidentiality and security of your devices and any credentials used to access our Service. Impierce Technologies B.V. is not liable for any loss or compromise of your data due to your failure to secure your device.
			Compliance with Laws: You agree to use our Service in compliance with all applicable laws and regulations.
			Accurate Information: You are responsible for ensuring that any information you store or share using our Service is accurate and up-to-date.
		
		
		
			Data Ownership and Privacy
			No Data Collection: We do not collect, store, or process any personal information through the UniMe application. All identity data remains solely on your device or within the storage option you choose.
			User-Controlled Sharing: Any data sharing is initiated and managed solely by you and occurs directly between you and the designated party. We do not access, track, or have insight into your identity or activity.
			Third-Party Data Collection: Be aware that third-party platforms like Apple App Store or Google Play Store may collect data related to app performance, usage, and device information independently of Impierce Technologies B.V.
		
		
		
			Intellectual Property Rights
			Ownership and Licensing: All intellectual property rights in UniMe and related materials are owned by Impierce Technologies B.V. or its licensors. However, UniMe is provided as an open-source product under the Apache 2.0 license, allowing users to use, modify, and distribute the software in compliance with the terms of that license.
			License Grant: By downloading or using UniMe, you agree to abide by the terms of the Apache 2.0 license, which grants a worldwide, royalty-free license to use, reproduce, and distribute the software with proper attribution.
		
			For more details, please refer to the full text of the Apache 2.0 License.
		
		
		
		
			Prohibited Activities
			You agree not to engage in any of the following activities:
			Unauthorized Access: Attempting to gain unauthorized access to our Service or systems.
			Interference: Disrupting or interfering with the security or performance of the Service.
			Misuse: Using the Service for any unlawful, harmful, fraudulent, infringing, or other malicious purposes.
		
		
		
			Third-Party Service
			Our Service may include links or integrations with third-party Services. We do not control these third-party Service and are not responsible for their content or policies. Your use of third-party Service is at your own risk and subject to their terms and conditions.
		
		
		
			Disclaimers
			“As Is” Basis: Our Service are provided on an “as is” and “as available” basis without warranties of any kind, either express or implied.
			No Warranty: We do not warrant that the Service will be uninterrupted, error-free, secure, or free from viruses or other harmful components.
		
		
		
			Limitation of Liability
			To the fullest extent permitted by law, Impierce Technologies B.V. shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses resulting from:
			Your access to or use of or inability to access or use the Service;
			Any conduct or content of any third party on the Service;
			Any content obtained from the Service.
		
		
		
			Indemnification
			You agree to indemnify, defend, and hold harmless Impierce Technologies B.V., its affiliates, and their respective directors, officers, employees, and agents from and against any claims, liabilities, damages, losses, and expenses arising out of or in any way connected with:
			Your access to or use of the Service;
			Your violation of these Terms;
			Your violation of any rights of another.
		
		
		
			Modifications to the Terms
			We may update or modify these Terms from time to time. The “Last Updated” date at the top indicates when the latest changes were made. We will notify you of significant changes by posting the new Terms on our website or through the Service. Your continued use of the Service after any changes constitute your acceptance of the new Terms.
		
		
		
			Governing Law and Jurisdiction
			These Terms are governed by and construed in accordance with the laws of the Netherlands. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in the Netherlands.
		
		
		
			Severability
			If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions will remain in full force and effect.
		
		
		
			Entire Agreement
			These Terms, along with our Privacy Policy, constitute the entire agreement between you and Impierce Technologies B.V. regarding your use of the Service.
		
		
		
			Contact Information
			For any questions, concerns, or comments about these Terms, please contact us at:
			Impierce Technologies B.V.
			Karekietweide 6, 3993 CD, Houten, the Netherlands
			Email: contact@impierce.com
		
		
		
			Language
			These Terms may have been translated into other languages for your convenience. In the event of a conflict between the English version and a translated version, the English version shall prevail.
		
			By using our Service, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions. Impierce Technologies B.V. remains committed to providing you with secure, privacy-centric solutions while upholding your rights and freedoms.
		
				 */
				FULL: () => LocalizedString
			}
			OWNERSHIP: {
				/**
				 * Data Ownership
				 */
				TITLE: () => LocalizedString
				/**
				 * I understand that I am solely responsible for my data.
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
		CUSTOMIZE: {
			/**
			 * Customization
			 */
			NAVBAR_TITLE: () => LocalizedString
			NAME: {
				/**
				 * Let's go! Choose a
				 */
				TITLE_1: () => LocalizedString
				/**
				 * profile name
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Your profile information will never leave your device.
				 */
				SUBTITLE: () => LocalizedString
				/**
				 * Enter a profile name
				 */
				INPUT_PLACEHOLDER: () => LocalizedString
			}
			PICTURE: {
				/**
				 * Set a display
				 */
				TITLE_1: () => LocalizedString
				/**
				 * picture
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Make it yours.
				 */
				SUBTITLE: () => LocalizedString
			}
		}
		PASSWORD: {
			/**
			 * Password
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * Set your new
			 */
			TITLE_1: () => LocalizedString
			/**
			 * password
			 */
			TITLE_2: () => LocalizedString
			/**
			 * You need to choose a strong password to securely encrypt your data.
			 */
			SUBTITLE: () => LocalizedString
			/**
			 * Enter a password
			 */
			INPUT_PLACEHOLDER: () => LocalizedString
			CONFIRM: {
				/**
				 * Confirm Password
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Please confirm your new
				 */
				TITLE_1: () => LocalizedString
				/**
				 * password
				 */
				TITLE_2: () => LocalizedString
				/**
				 * You need to confirm your password to make sure you typed it correctly.
				 */
				SUBTITLE: () => LocalizedString
				/**
				 * Retype your password
				 */
				INPUT_PLACEHOLDER: () => LocalizedString
				/**
				 * Passwords match
				 */
				MATCH: () => LocalizedString
				/**
				 * Passwords do not match
				 */
				NO_MATCH: () => LocalizedString
			}
			BIOMETRICS: {
				/**
				 * Enable {type}
				 */
				TITLE: (arg: { type: string }) => LocalizedString
				/**
				 * Do you want to set up {type} to unlock the app?
				 */
				DESCRIPTION: (arg: { type: string }) => LocalizedString
				/**
				 * Yes, use {type}
				 */
				CONFIRM: (arg: { type: string }) => LocalizedString
				/**
				 * Decide later
				 */
				DECIDE_LATER: () => LocalizedString
			}
			COMPLETED: {
				/**
				 * Password Set
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Your UniMe profile is now
				 */
				TITLE_1: () => LocalizedString
				/**
				 * protected
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Safe & Secure.
				 */
				MESSAGE_1: () => LocalizedString
				/**
				 * Nice Job
				 */
				MESSAGE_2: () => LocalizedString
			}
		}
	}
	SETTINGS: {
		/**
		 * Settings
		 */
		NAVBAR_TITLE: () => LocalizedString
		PROFILE: {
			/**
			 * My profile
			 */
			TITLE: () => LocalizedString
			PROFILE_NAME: {
				/**
				 * Profile name
				 */
				TITLE: () => LocalizedString
				/**
				 * Change profile name
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Enter a profile name
				 */
				INPUT_PLACEHOLDER: () => LocalizedString
				/**
				 * Update
				 */
				CONFIRM: () => LocalizedString
			}
			DISPLAY_PICTURE: {
				/**
				 * Edit
				 */
				EDIT: () => LocalizedString
				/**
				 * Select a profile picture
				 */
				CHANGE: () => LocalizedString
				/**
				 * Remove
				 */
				REMOVE: () => LocalizedString
			}
			DELETE_PROFILE: {
				/**
				 * Delete profile
				 */
				TITLE: () => LocalizedString
			}
		}
		APP: {
			/**
			 * App settings
			 */
			TITLE: () => LocalizedString
			/**
			 * App Settings
			 */
			NAVBAR_TITLE: () => LocalizedString
			LANGUAGE: {
				/**
				 * Language
				 */
				TITLE: () => LocalizedString
				/**
				 * Select Language
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Coming soon
				 */
				COMING_SOON: () => LocalizedString
			}
			THEME: {
				/**
				 * Theme
				 */
				LABEL: () => LocalizedString
				/**
				 * Select Theme
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Choose your app
				 */
				TITLE_1: () => LocalizedString
				/**
				 * appearance
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Are you more of a night owl?
				 */
				SUBTITLE: () => LocalizedString
			}
			SECURITY: {
				/**
				 * Security
				 */
				LABEL: () => LocalizedString
				/**
				 * Security
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Unlock with {type}
				 */
				SWITCH_LABEL: (arg: { type: string }) => LocalizedString
				BIOMETRIC_TYPE: {
					ANDROID: {
						/**
						 * facial recognition
						 */
						FACE_ID: () => LocalizedString
						/**
						 * fingerprint
						 */
						TOUCH_ID: () => LocalizedString
					}
					IOS: {
						/**
						 * Face ID
						 */
						FACE_ID: () => LocalizedString
						/**
						 * Touch ID
						 */
						TOUCH_ID: () => LocalizedString
					}
					/**
					 * biometrics
					 */
					GENERIC: () => LocalizedString
				}
				ENABLE: {
					/**
					 * Enable {type}
					 */
					DIALOG_TITLE: (arg: { type: string }) => LocalizedString
					/**
					 * Please enter your password to enable {type}.
					 */
					DIALOG_CONTENT: (arg: { type: string }) => LocalizedString
				}
				DISABLE: {
					/**
					 * Disable {type}
					 */
					DIALOG_TITLE: (arg: { type: string }) => LocalizedString
					/**
					 * Please enter your password to disable {type}.
					 */
					DIALOG_CONTENT: (arg: { type: string }) => LocalizedString
				}
			}
			PASSWORD: {
				/**
				 * Password
				 */
				TITLE: () => LocalizedString
			}
			ONBOARDING_JOURNEY: {
				/**
				 * Onboarding journey
				 */
				TITLE: () => LocalizedString
				/**
				 * Restart
				 */
				BUTTON_TEXT: () => LocalizedString
			}
			HINTS_AND_TIPS: {
				/**
				 * Hints and tips
				 */
				TITLE: () => LocalizedString
				/**
				 * Reset
				 */
				BUTTON_TEXT: () => LocalizedString
			}
			DEVELOPER_MODE: {
				/**
				 * Developer mode
				 */
				TITLE: () => LocalizedString
			}
		}
		BACKUP_RECOVERY: {
			/**
			 * Backup and recovery
			 */
			TITLE: () => LocalizedString
		}
		LOG_OUT: {
			/**
			 * Log out
			 */
			TITLE: () => LocalizedString
		}
		THEME: {
			/**
			 * System
			 */
			SYSTEM: () => LocalizedString
			/**
			 * Light
			 */
			LIGHT: () => LocalizedString
			/**
			 * Dark
			 */
			DARK: () => LocalizedString
		}
		PASSWORD: {
			POLICY: {
				/**
				 * Your password must contain
				 */
				TITLE: () => LocalizedString
				/**
				 * uppercase letter
				 */
				UPPERCASE_LETTER: () => LocalizedString
				/**
				 * lowercase letter
				 */
				LOWERCASE_LETTER: () => LocalizedString
				/**
				 * number
				 */
				NUMBER: () => LocalizedString
				/**
				 * characters
				 */
				CHARACTERS: () => LocalizedString
			}
		}
		RESET_APP: {
			/**
			 * Reset app
			 */
			TITLE: () => LocalizedString
			/**
			 * Are you sure you want to reset the app and remove all data?
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Yes, delete everything
			 */
			CONFIRM: () => LocalizedString
			/**
			 * No, keep my profile
			 */
			CANCEL: () => LocalizedString
		}
		/**
		 * Account
		 */
		ACCOUNT: () => LocalizedString
		SUPPORT: {
			/**
			 * Support
			 */
			TITLE: () => LocalizedString
			ABOUT: {
				/**
				 * About UniMe
				 */
				TITLE: () => LocalizedString
				/**
				 * About UniMe
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Specifications
				 */
				SPECIFICATIONS: () => LocalizedString
				/**
				 * Version
				 */
				VERSION: () => LocalizedString
				/**
				 * License
				 */
				LICENSE: () => LocalizedString
				/**
				 * Built with Tauri
				 */
				BUILT_WITH: () => LocalizedString
			}
			FEEDBACK: {
				/**
				 * Send feedback
				 */
				TITLE: () => LocalizedString
			}
		}
	}
	LOCK_SCREEN: {
		/**
		 * Enter your password
		 */
		PASSWORD_INPUT_PLACEHOLDER: () => LocalizedString
		/**
		 * Unlock wallet
		 */
		BUTTON_TEXT: () => LocalizedString
		/**
		 * Forgot password?
		 */
		FORGOT_PASSWORD: () => LocalizedString
	}
	ME: {
		/**
		 * Me
		 */
		BOTTOM_NAVIGATION_TITLE: () => LocalizedString
		GREETINGS: {
			/**
			 * Hey
			 */
			GREETING_0: () => LocalizedString
			/**
			 * What's up
			 */
			GREETING_1: () => LocalizedString
			/**
			 * How are you
			 */
			GREETING_2: () => LocalizedString
			/**
			 * Welcome back
			 */
			GREETING_3: () => LocalizedString
			/**
			 * Hello
			 */
			GREETING_4: () => LocalizedString
		}
		CREDENTIAL_TABS: {
			/**
			 * All
			 */
			ALL: () => LocalizedString
			/**
			 * Data
			 */
			DATA: () => LocalizedString
			/**
			 * Badges
			 */
			BADGES: () => LocalizedString
		}
		EMPTY_CREDENTIALS: {
			/**
			 * It's a bit quiet in here
			 */
			TITLE: () => LocalizedString
			/**
			 * Why not get some of your data verified to start your journey?
			 */
			SUBTITLE: () => LocalizedString
		}
		/**
		 * My favorites
		 */
		FAVORITES: () => LocalizedString
	}
	ACTIVITY: {
		/**
		 * Activity
		 */
		BOTTOM_NAVIGATION_TITLE: () => LocalizedString
		/**
		 * Connected
		 */
		NAVBAR_TITLE: () => LocalizedString
		TABS: {
			/**
			 * Connections
			 */
			CONNECTIONS: () => LocalizedString
			/**
			 * History
			 */
			HISTORY: () => LocalizedString
		}
	}
	SCAN: {
		/**
		 * Scan
		 */
		BOTTOM_NAVIGATION_TITLE: () => LocalizedString
		/**
		 * Scan a
		 */
		TITLE_1: () => LocalizedString
		/**
		 * QR Code
		 */
		TITLE_2: () => LocalizedString
		/**
		 * Bring a QR Code into view of this screen to start an interaction.
		 */
		SUBTITLE: () => LocalizedString
		/**
		 * No permission to access the camera
		 */
		PERMISSION_DENIED: () => LocalizedString
		/**
		 * Open settings
		 */
		OPEN_SETTINGS: () => LocalizedString
		CREDENTIAL_OFFER: {
			/**
			 * Credential Offer
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * is offering you the following credentials
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Accept credentials
			 */
			ACCEPT: () => LocalizedString
		}
		CONNECTION_REQUEST: {
			/**
			 * Connection Request
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * New connection
			 */
			TITLE: () => LocalizedString
			/**
			 * Only accept new connections that you recognize and trust
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Connected previously
			 */
			CONNECTED_PREVIOUSLY: () => LocalizedString
			/**
			 * Accept connection
			 */
			ACCEPT: () => LocalizedString
		}
		SHARE_CREDENTIALS: {
			/**
			 * Share Data
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * requests the following credentials
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Requested
			 */
			REQUESTED: () => LocalizedString
			/**
			 * Approve request
			 */
			APPROVE: () => LocalizedString
		}
	}
	CONNECTION: {
		TABS: {
			/**
			 * Summary
			 */
			SUMMARY: () => LocalizedString
			/**
			 * Data
			 */
			DATA: () => LocalizedString
			/**
			 * Activity
			 */
			ACTIVITY: () => LocalizedString
		}
		SUMMARY: {
			/**
			 * No connections yet.
			 */
			EMPTY: () => LocalizedString
			/**
			 * Connected to
			 */
			TITLE: () => LocalizedString
			/**
			 * First connected
			 */
			FIRST_CONNECTED: () => LocalizedString
			/**
			 * Last connected
			 */
			LAST_CONNECTED: () => LocalizedString
		}
		DATA: {
			/**
			 * No data yet.
			 */
			EMPTY: () => LocalizedString
		}
	}
	HISTORY: {
		/**
		 * No activity yet.
		 */
		EMPTY: () => LocalizedString
		/**
		 * Received data from
		 */
		DATA_RECEIVED: () => LocalizedString
		/**
		 * Shared data with
		 */
		DATA_SHARED: () => LocalizedString
		/**
		 * Connected to
		 */
		CONNECTION_ADDED: () => LocalizedString
	}
	SEARCH: {
		/**
		 * Search for something
		 */
		INPUT_PLACEHOLDER: () => LocalizedString
		NO_QUERY: {
			/**
			 * What shall we search for?
			 */
			TITLE: () => LocalizedString
			/**
			 * Search for any of your credentials and badges here.
			 */
			DESCRIPTION: () => LocalizedString
		}
		NO_RESULTS: {
			/**
			 * No results found
			 */
			TITLE: () => LocalizedString
			/**
			 * Try searching for something else.
			 */
			DESCRIPTION: () => LocalizedString
		}
		/**
		 * Recent searches
		 */
		RECENT_SEARCHES: () => LocalizedString
	}
	CREDENTIAL: {
		/**
		 * Credential Information
		 */
		NAVBAR_TITLE: () => LocalizedString
		DETAILS: {
			/**
			 * Valid
			 */
			VALID: () => LocalizedString
			/**
			 * Issued by
			 */
			ISSUED_BY: () => LocalizedString
			/**
			 * Description
			 */
			DESCRIPTION: () => LocalizedString
			OPEN_BADGES: {
				/**
				 * Alignment
				 */
				ALIGNMENT: () => LocalizedString
				/**
				 * Criteria
				 */
				CRITERIA: () => LocalizedString
			}
		}
		ACTIONS: {
			DELETE: {
				/**
				 * Delete credential
				 */
				BUTTON_LABEL: () => LocalizedString
				/**
				 * Delete credential
				 */
				TITLE: () => LocalizedString
				/**
				 * Are you sure you want to delete this credential from your wallet? This action cannot be undone.
				 */
				DESCRIPTION: () => LocalizedString
				/**
				 * Delete
				 */
				CONFIRM_BUTTON: () => LocalizedString
			}
		}
	}
	ADD_CREDENTIALS: {
		/**
		 * Add
		 */
		BUTTON: () => LocalizedString
		/**
		 * Add data
		 */
		NAVBAR_TITLE: () => LocalizedString
		EMAIL: {
			/**
			 * Email
			 */
			TITLE: () => LocalizedString
			/**
			 * Get your personal or work email verified
			 */
			DESCRIPTION: () => LocalizedString
			INFO: {
				/**
				 * Verified email
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Verified email
				 */
				TITLE: () => LocalizedString
				/**
				 * Before you start
				 */
				DESCRIPTION: () => LocalizedString
				ITEM_0: {
					/**
					 * What can I do with my verified email?
					 */
					TITLE: () => LocalizedString
					/**
					 * You can prove ownership of that email address to websites, shops and other people. It also allows you to log in to websites that support it without needing to remember a password or setting up a passkey.
					 */
					DESCRIPTION: () => LocalizedString
				}
				ITEM_1: {
					/**
					 * How is it verified?
					 */
					TITLE: () => LocalizedString
					/**
					 * UniMe sends a message containing your email to a verification system run by us. That system then sends an email containing a one-time code to your inbox. By entering that code in UniMe, you prove you have access to that email inbox. UniMe then sends another message to our verification system, redeeming that code for a verifiable credential.
					 */
					DESCRIPTION: () => LocalizedString
				}
				ITEM_2: {
					/**
					 * Is my personal information safe?
					 */
					TITLE: () => LocalizedString
					/**
					 * We treat any data you enter in UniMe with the greatest respect. All messages from UniMe to our servers are fully encrypted when they travel through the internet. They are also encrypted on our servers using the latest security standards. In order to successfully deliver an email to your inbox, we initially have to receive it in plain text, so a full "zero-access encryption" is unfortunately not applicable to this use case.
					 */
					DESCRIPTION: () => LocalizedString
				}
			}
			ADD: {
				/**
				 * Get verified email
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Your UniMe label
				 */
				LABEL: () => LocalizedString
				/**
				 * Only seen by you
				 */
				LABEL_DISCLAIMER: () => LocalizedString
				/**
				 * Personal email
				 */
				LABEL_PLACEHOLDER: () => LocalizedString
				/**
				 * Email
				 */
				VALUE_LABEL: () => LocalizedString
				/**
				 * firstname.lastname@example.com
				 */
				VALUE_PLACEHOLDER: () => LocalizedString
				/**
				 * Send verification email
				 */
				BUTTON_SEND: () => LocalizedString
				/**
				 * Resend verification email
				 */
				BUTTON_SEND_AGAIN: () => LocalizedString
			}
		}
	}
	SORT: {
		/**
		 * Sorting
		 */
		TITLE: () => LocalizedString
		PREFERENCES: {
			/**
			 * List View
			 */
			LIST_VIEW: () => LocalizedString
			/**
			 * Grid View
			 */
			GRID_VIEW: () => LocalizedString
			/**
			 * Alphabetical
			 */
			ALPHABETICAL: () => LocalizedString
			/**
			 * Date Issued
			 */
			DATE_ISSUED: () => LocalizedString
			/**
			 * Date Added
			 */
			DATE_ADDED: () => LocalizedString
		}
		ORDER: {
			/**
			 * A to Z
			 */
			A_Z: () => LocalizedString
			/**
			 * Z to A
			 */
			Z_A: () => LocalizedString
			/**
			 * Newest first
			 */
			NEWEST: () => LocalizedString
			/**
			 * Oldest first
			 */
			OLDEST: () => LocalizedString
		}
	}
	DOMAIN_LINKAGE: {
		/**
		 * Verified website
		 */
		TITLE: () => LocalizedString
		/**
		 * UniMe successfully verified the identity to provide you with a secure login.
		 */
		SUCCESS: () => LocalizedString
		/**
		 * UniMe could not verify the linkage of the identity to the domain.
		 */
		FAILURE: () => LocalizedString
		/**
		 * UniMe could not find any proof of the domain's associated identity.
		 */
		UNKNOWN: () => LocalizedString
		/**
		 * Proceed with caution!
		 */
		CAUTION: () => LocalizedString
	}
	ERROR: {
		/**
		 * Oops!
		 */
		TITLE: () => LocalizedString
		/**
		 * Something went wrong. Please try again.
		 */
		DEFAULT_MESSAGE: () => LocalizedString
	}
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Close
	 */
	CLOSE: () => LocalizedString
	/**
	 * Discard
	 */
	DISCARD: () => LocalizedString
	/**
	 * Continue
	 */
	CONTINUE: () => LocalizedString
	/**
	 * Skip
	 */
	SKIP: () => LocalizedString
	/**
	 * Accept
	 */
	ACCEPT: () => LocalizedString
	/**
	 * Reject
	 */
	REJECT: () => LocalizedString
	GETTING_STARTED: {
		/**
		 * Skip Getting Started
		 */
		SKIP_TITLE: () => LocalizedString
		/**
		 * Are you sure you want to skip the getting started guide?
		 */
		SKIP_TEXT: () => LocalizedString
	}
}

export type Formatters = {}
