// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de-DE'
	| 'en'
	| 'en-GB'
	| 'en-US'
	| 'nl-NL'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	ONBOARDING: {
		WELCOME: {
			/**
			 * W​e​l​c​o​m​e​ ​t​o
			 */
			GREETING: string
			/**
			 * U​n​i​M​e​ ​c​o​n​n​e​c​t​s​ ​y​o​u​r​ ​d​i​g​i​t​a​l​ ​w​o​r​l​d​,​ ​s​a​f​e​l​y​ ​a​n​d​ ​s​e​c​u​r​e​l​y​.
			 */
			WHAT_IS_UNIME_1: string
			/**
			 * C​r​e​a​t​e​ ​a​ ​b​r​a​n​d​ ​n​e​w​ ​i​d​e​n​t​i​t​y​ ​p​r​o​f​i​l​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
			 */
			WHAT_IS_UNIME_2: string
			/**
			 * C​r​e​a​t​e​ ​n​e​w​ ​p​r​o​f​i​l​e
			 */
			CREATE_NEW_PROFILE: string
			/**
			 * S​e​l​e​c​t​ ​l​a​n​g​u​a​g​e
			 */
			SELECT_LANGUAGE: string
		}
		PLEDGE: {
			/**
			 * U​n​i​M​e​ ​P​l​e​d​g​e
			 */
			NAVBAR_TITLE: string
			/**
			 * N​o​ ​f​u​n​n​y
			 */
			TITLE_1: string
			/**
			 * b​u​s​i​n​e​s​s
			 */
			TITLE_2: string
			/**
			 * H​e​r​e​'​s​ ​o​u​r​ ​p​l​e​d​g​e​ ​t​o​ ​y​o​u​.
			 */
			SUBTITLE: string
			ITEM_1: {
				/**
				 * W​e​ ​w​i​l​l​ ​n​o​t​ ​s​h​a​r​e​ ​y​o​u​r​ ​d​a​t​a
				 */
				TITLE: string
				/**
				 * Y​o​u​r​ ​d​a​t​a​ ​b​e​l​o​n​g​s​ ​t​o​ ​y​o​u​ ​a​n​d​ ​o​n​l​y​ ​y​o​u​ ​d​e​c​i​d​e​ ​w​h​o​ ​y​o​u​ ​s​h​a​r​e​ ​i​t​ ​w​i​t​h​.​ ​P​e​r​i​o​d​.​ ​I​n​ ​f​a​c​t​,​ ​y​o​u​r​ ​d​a​t​a​ ​n​e​v​e​r​ ​e​v​e​n​ ​t​o​u​c​h​e​s​ ​a​n​y​ ​o​f​ ​o​u​r​ ​s​y​s​t​e​m​s​ ​-​ ​u​n​l​e​s​s​ ​y​o​u​ ​o​p​t​-​i​n​ ​t​o​ ​o​n​e​ ​o​f​ ​t​h​e​ ​c​l​o​u​d​ ​s​t​o​r​a​g​e​ ​o​p​t​i​o​n​s​.
				 */
				DESCRIPTION: string
			}
			ITEM_2: {
				/**
				 * W​e​ ​w​i​l​l​ ​n​o​t​ ​a​d​d​ ​t​r​a​c​k​e​r​s
				 */
				TITLE: string
				/**
				 * W​e​ ​d​o​ ​n​o​t​ ​t​r​a​c​k​ ​y​o​u​r​ ​a​c​t​i​o​n​s​ ​b​e​h​i​n​d​ ​t​h​e​ ​s​c​e​n​e​s​.​ ​P​e​r​i​o​d​.​ ​N​o​t​ ​f​o​r​ ​t​e​s​t​i​n​g​ ​o​r​ ​a​n​y​ ​o​t​h​e​r​ ​r​e​a​s​o​n​s​.​ ​T​h​a​t​'​s​ ​o​u​r​ ​p​l​e​d​g​e​.​ ​W​e​ ​a​l​s​o​ ​d​o​ ​n​o​t​ ​c​o​l​l​e​c​t​ ​a​n​y​ ​a​n​o​n​y​m​o​u​s​ ​d​e​v​i​c​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​o​r​ ​u​s​a​g​e​ ​s​t​a​t​i​s​t​i​c​s​.​ ​T​h​a​t​ ​d​e​c​i​s​i​o​n​ ​m​a​k​e​s​ ​d​e​v​e​l​o​p​i​n​g​ ​t​h​e​ ​a​p​p​ ​a​ ​b​i​t​ ​h​a​r​d​e​r​ ​f​o​r​ ​u​s​,​ ​b​u​t​ ​w​e​ ​b​e​l​i​e​v​e​ ​i​t​ ​i​s​ ​t​h​e​ ​r​i​g​h​t​ ​d​e​c​i​s​i​o​n​.
				 */
				DESCRIPTION: string
			}
			ITEM_3: {
				/**
				 * Y​o​u​ ​o​w​n​ ​y​o​u​r​ ​i​n​f​o​r​m​a​t​i​o​n
				 */
				TITLE: string
				/**
				 * W​e​ ​b​e​l​i​e​v​e​ ​t​h​a​t​ ​i​t​'​s​ ​a​b​o​u​t​ ​t​i​m​e​ ​y​o​u​ ​b​e​c​o​m​e​ ​t​h​e​ ​o​w​n​e​r​ ​o​f​ ​y​o​u​r​ ​o​w​n​ ​p​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​g​a​i​n​.
				 */
				DESCRIPTION: string
			}
		}
		TERMS: {
			/**
			 * T​e​r​m​s​ ​&​ ​C​o​n​d​i​t​i​o​n​s
			 */
			NAVBAR_TITLE: string
			/**
			 * H​e​r​e​'​s​ ​t​h​e​ ​l​e​s​s​ ​i​n​t​e​r​e​s​t​i​n​g
			 */
			TITLE_1: string
			/**
			 * s​t​u​f​f
			 */
			TITLE_2: string
			/**
			 * Y​e​a​h​,​ ​w​e​ ​k​n​o​w​.​ ​W​e​ ​s​t​i​l​l​ ​r​e​c​o​m​m​e​n​d​ ​y​o​u​ ​r​e​a​d​ ​t​h​i​s​ ​i​n​f​o​r​m​a​t​i​o​n​ ​c​a​r​e​f​u​l​l​y​.
			 */
			SUBTITLE: string
			OWNERSHIP: {
				/**
				 * O​w​n​e​r​s​h​i​p
				 */
				TITLE: string
				/**
				 * I​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​a​t​ ​I​ ​a​m​ ​s​o​l​e​l​y​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​m​y​ ​d​a​t​a​.
				 */
				DESCRIPTION: string
			}
		}
		CUSTOMIZE: {
			/**
			 * C​u​s​t​o​m​i​z​a​t​i​o​n
			 */
			NAVBAR_TITLE: string
			NAME: {
				/**
				 * L​e​t​'​s​ ​g​o​!​ ​C​h​o​o​s​e​ ​a
				 */
				TITLE_1: string
				/**
				 * p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				TITLE_2: string
				/**
				 * Y​o​u​r​ ​p​r​o​f​i​l​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​w​i​l​l​ ​n​e​v​e​r​ ​l​e​a​v​e​ ​y​o​u​r​ ​d​e​v​i​c​e​.
				 */
				SUBTITLE: string
				/**
				 * E​n​t​e​r​ ​a​ ​p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				INPUT_PLACEHOLDER: string
			}
			PICTURE: {
				/**
				 * S​e​t​ ​a​ ​d​i​s​p​l​a​y
				 */
				TITLE_1: string
				/**
				 * p​i​c​t​u​r​e
				 */
				TITLE_2: string
				/**
				 * M​a​k​e​ ​i​t​ ​y​o​u​r​s​.
				 */
				SUBTITLE: string
			}
		}
		PASSWORD: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			NAVBAR_TITLE: string
			/**
			 * S​e​t​ ​y​o​u​r​ ​n​e​w
			 */
			TITLE_1: string
			/**
			 * p​a​s​s​w​o​r​d
			 */
			TITLE_2: string
			/**
			 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​c​h​o​o​s​e​ ​a​ ​s​t​r​o​n​g​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​s​e​c​u​r​e​l​y​ ​e​n​c​r​y​p​t​ ​y​o​u​r​ ​d​a​t​a​.
			 */
			SUBTITLE: string
			/**
			 * E​n​t​e​r​ ​a​ ​p​a​s​s​w​o​r​d
			 */
			INPUT_PLACEHOLDER: string
			CONFIRM: {
				/**
				 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
				 */
				NAVBAR_TITLE: string
				/**
				 * P​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​n​e​w
				 */
				TITLE_1: string
				/**
				 * p​a​s​s​w​o​r​d
				 */
				TITLE_2: string
				/**
				 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​t​o​ ​m​a​k​e​ ​s​u​r​e​ ​y​o​u​ ​t​y​p​e​d​ ​i​t​ ​c​o​r​r​e​c​t​l​y​.
				 */
				SUBTITLE: string
				/**
				 * R​e​t​y​p​e​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
				 */
				INPUT_PLACEHOLDER: string
				/**
				 * P​a​s​s​w​o​r​d​s​ ​m​a​t​c​h
				 */
				MATCH: string
				/**
				 * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
				 */
				NO_MATCH: string
			}
			COMPLETED: {
				/**
				 * P​a​s​s​w​o​r​d​ ​S​e​t
				 */
				NAVBAR_TITLE: string
				/**
				 * Y​o​u​r​ ​U​n​i​M​e​ ​p​r​o​f​i​l​e​ ​i​s​ ​n​o​w
				 */
				TITLE_1: string
				/**
				 * p​r​o​t​e​c​t​e​d
				 */
				TITLE_2: string
				/**
				 * S​a​f​e​ ​&​ ​S​e​c​u​r​e​.
				 */
				MESSAGE_1: string
				/**
				 * N​i​c​e​ ​J​o​b
				 */
				MESSAGE_2: string
			}
		}
	}
	SETTINGS: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		NAVBAR_TITLE: string
		PROFILE: {
			/**
			 * M​y​ ​p​r​o​f​i​l​e
			 */
			TITLE: string
			PROFILE_NAME: {
				/**
				 * P​r​o​f​i​l​e​ ​n​a​m​e
				 */
				TITLE: string
				/**
				 * C​h​a​n​g​e​ ​p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				NAVBAR_TITLE: string
				/**
				 * E​n​t​e​r​ ​a​ ​p​r​o​f​i​l​e​ ​n​a​m​e
				 */
				INPUT_PLACEHOLDER: string
				/**
				 * U​p​d​a​t​e
				 */
				CONFIRM: string
			}
			DISPLAY_PICTURE: {
				/**
				 * E​d​i​t
				 */
				EDIT: string
				/**
				 * S​e​l​e​c​t​ ​a​ ​p​r​o​f​i​l​e​ ​p​i​c​t​u​r​e
				 */
				CHANGE: string
				/**
				 * R​e​m​o​v​e
				 */
				REMOVE: string
			}
			DELETE_PROFILE: {
				/**
				 * D​e​l​e​t​e​ ​p​r​o​f​i​l​e
				 */
				TITLE: string
			}
		}
		APP: {
			/**
			 * A​p​p​ ​s​e​t​t​i​n​g​s
			 */
			TITLE: string
			/**
			 * A​p​p​ ​S​e​t​t​i​n​g​s
			 */
			NAVBAR_TITLE: string
			LANGUAGE: {
				/**
				 * L​a​n​g​u​a​g​e
				 */
				TITLE: string
				/**
				 * S​e​l​e​c​t​ ​L​a​n​g​u​a​g​e
				 */
				NAVBAR_TITLE: string
				/**
				 * C​o​m​i​n​g​ ​s​o​o​n
				 */
				COMING_SOON: string
			}
			THEME: {
				/**
				 * T​h​e​m​e
				 */
				LABEL: string
				/**
				 * S​e​l​e​c​t​ ​T​h​e​m​e
				 */
				NAVBAR_TITLE: string
				/**
				 * C​h​o​o​s​e​ ​y​o​u​r​ ​a​p​p
				 */
				TITLE_1: string
				/**
				 * a​p​p​e​a​r​a​n​c​e
				 */
				TITLE_2: string
				/**
				 * A​r​e​ ​y​o​u​ ​m​o​r​e​ ​o​f​ ​a​ ​n​i​g​h​t​ ​o​w​l​?
				 */
				SUBTITLE: string
			}
			PASSWORD: {
				/**
				 * P​a​s​s​w​o​r​d
				 */
				TITLE: string
			}
			ONBOARDING_JOURNEY: {
				/**
				 * O​n​b​o​a​r​d​i​n​g​ ​j​o​u​r​n​e​y
				 */
				TITLE: string
				/**
				 * R​e​s​t​a​r​t
				 */
				BUTTON_TEXT: string
			}
			HINTS_AND_TIPS: {
				/**
				 * H​i​n​t​s​ ​a​n​d​ ​t​i​p​s
				 */
				TITLE: string
				/**
				 * R​e​s​e​t
				 */
				BUTTON_TEXT: string
			}
			DEVELOPER_MODE: {
				/**
				 * D​e​v​e​l​o​p​e​r​ ​m​o​d​e
				 */
				TITLE: string
			}
		}
		BACKUP_RECOVERY: {
			/**
			 * B​a​c​k​u​p​ ​a​n​d​ ​r​e​c​o​v​e​r​y
			 */
			TITLE: string
		}
		LOG_OUT: {
			/**
			 * L​o​g​ ​o​u​t
			 */
			TITLE: string
		}
		THEME: {
			/**
			 * S​y​s​t​e​m
			 */
			SYSTEM: string
			/**
			 * L​i​g​h​t
			 */
			LIGHT: string
			/**
			 * D​a​r​k
			 */
			DARK: string
		}
		PASSWORD: {
			POLICY: {
				/**
				 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n
				 */
				TITLE: string
				/**
				 * u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r
				 */
				UPPERCASE_LETTER: string
				/**
				 * l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r
				 */
				LOWERCASE_LETTER: string
				/**
				 * n​u​m​b​e​r
				 */
				NUMBER: string
				/**
				 * c​h​a​r​a​c​t​e​r​s
				 */
				CHARACTERS: string
			}
		}
		RESET_APP: {
			/**
			 * R​e​s​e​t​ ​a​p​p
			 */
			TITLE: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​s​e​t​ ​t​h​e​ ​a​p​p​ ​a​n​d​ ​r​e​m​o​v​e​ ​a​l​l​ ​d​a​t​a​?
			 */
			DESCRIPTION: string
			/**
			 * Y​e​s​,​ ​d​e​l​e​t​e​ ​e​v​e​r​y​t​h​i​n​g
			 */
			CONFIRM: string
			/**
			 * N​o​,​ ​k​e​e​p​ ​m​y​ ​p​r​o​f​i​l​e
			 */
			CANCEL: string
		}
		/**
		 * A​c​c​o​u​n​t
		 */
		ACCOUNT: string
		SUPPORT: {
			/**
			 * S​u​p​p​o​r​t
			 */
			TITLE: string
			ABOUT: {
				/**
				 * A​b​o​u​t​ ​U​n​i​M​e
				 */
				TITLE: string
				/**
				 * A​b​o​u​t​ ​U​n​i​M​e
				 */
				NAVBAR_TITLE: string
				/**
				 * S​p​e​c​i​f​i​c​a​t​i​o​n​s
				 */
				SPECIFICATIONS: string
				/**
				 * V​e​r​s​i​o​n
				 */
				VERSION: string
				/**
				 * L​i​c​e​n​s​e
				 */
				LICENSE: string
				/**
				 * B​u​i​l​t​ ​w​i​t​h​ ​T​a​u​r​i
				 */
				BUILT_WITH: string
			}
			FEEDBACK: {
				/**
				 * S​e​n​d​ ​f​e​e​d​b​a​c​k
				 */
				TITLE: string
			}
		}
	}
	LOCK_SCREEN: {
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
		 */
		PASSWORD_INPUT_PLACEHOLDER: string
		/**
		 * U​n​l​o​c​k​ ​w​a​l​l​e​t
		 */
		BUTTON_TEXT: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
		 */
		FORGOT_PASSWORD: string
	}
	ME: {
		/**
		 * M​e
		 */
		BOTTOM_NAVIGATION_TITLE: string
		GREETINGS: {
			/**
			 * H​e​y
			 */
			GREETING_0: string
			/**
			 * W​h​a​t​'​s​ ​u​p
			 */
			GREETING_1: string
			/**
			 * H​o​w​ ​a​r​e​ ​y​o​u
			 */
			GREETING_2: string
			/**
			 * W​e​l​c​o​m​e​ ​b​a​c​k
			 */
			GREETING_3: string
			/**
			 * H​e​l​l​o
			 */
			GREETING_4: string
		}
		/**
		 * V​i​s​i​t​ ​o​n​e​ ​o​f​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​w​e​b​s​i​t​e​s​ ​o​n​ ​a​ ​d​e​s​k​t​o​p​ ​c​o​m​p​u​t​e​r​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
		 */
		DEMO: string
		CREDENTIAL_TABS: {
			/**
			 * A​l​l
			 */
			ALL: string
			/**
			 * D​a​t​a
			 */
			DATA: string
			/**
			 * B​a​d​g​e​s
			 */
			BADGES: string
		}
		EMPTY_CREDENTIALS: {
			/**
			 * I​t​'​s​ ​a​ ​b​i​t​ ​q​u​i​e​t​ ​i​n​ ​h​e​r​e
			 */
			TITLE: string
			/**
			 * W​h​y​ ​n​o​t​ ​a​d​d​ ​s​o​m​e​ ​c​r​e​d​e​n​t​i​a​l​s​ ​t​o​ ​s​t​a​r​t​ ​y​o​u​r​ ​n​e​w​ ​d​i​g​i​t​a​l​ ​m​e​?
			 */
			SUBTITLE: string
		}
		/**
		 * M​y​ ​f​a​v​o​r​i​t​e​s
		 */
		FAVORITES: string
	}
	ACTIVITY: {
		/**
		 * A​c​t​i​v​i​t​y
		 */
		BOTTOM_NAVIGATION_TITLE: string
		/**
		 * C​o​n​n​e​c​t​e​d
		 */
		NAVBAR_TITLE: string
		TABS: {
			/**
			 * C​o​n​n​e​c​t​i​o​n​s
			 */
			CONNECTIONS: string
			/**
			 * H​i​s​t​o​r​y
			 */
			HISTORY: string
		}
	}
	SCAN: {
		/**
		 * S​c​a​n
		 */
		BOTTOM_NAVIGATION_TITLE: string
		/**
		 * S​c​a​n​ ​a
		 */
		TITLE_1: string
		/**
		 * Q​R​ ​C​o​d​e
		 */
		TITLE_2: string
		/**
		 * B​r​i​n​g​ ​a​ ​Q​R​ ​C​o​d​e​ ​i​n​t​o​ ​v​i​e​w​ ​o​f​ ​t​h​i​s​ ​s​c​r​e​e​n​ ​t​o​ ​s​t​a​r​t​ ​a​n​ ​i​n​t​e​r​a​c​t​i​o​n​.
		 */
		SUBTITLE: string
		/**
		 * N​o​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​e​ ​c​a​m​e​r​a
		 */
		PERMISSION_DENIED: string
		/**
		 * O​p​e​n​ ​s​e​t​t​i​n​g​s
		 */
		OPEN_SETTINGS: string
		CREDENTIAL_OFFER: {
			/**
			 * C​r​e​d​e​n​t​i​a​l​ ​O​f​f​e​r
			 */
			NAVBAR_TITLE: string
			/**
			 * i​s​ ​o​f​f​e​r​i​n​g​ ​y​o​u​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			DESCRIPTION: string
			/**
			 * A​c​c​e​p​t​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			ACCEPT: string
		}
		CONNECTION_REQUEST: {
			/**
			 * C​o​n​n​e​c​t​i​o​n​ ​R​e​q​u​e​s​t
			 */
			NAVBAR_TITLE: string
			/**
			 * N​e​w​ ​c​o​n​n​e​c​t​i​o​n
			 */
			TITLE: string
			/**
			 * O​n​l​y​ ​a​c​c​e​p​t​ ​n​e​w​ ​c​o​n​n​e​c​t​i​o​n​s​ ​t​h​a​t​ ​y​o​u​ ​r​e​c​o​g​n​i​z​e​ ​a​n​d​ ​t​r​u​s​t
			 */
			DESCRIPTION: string
			/**
			 * C​o​n​n​e​c​t​e​d​ ​p​r​e​v​i​o​u​s​l​y
			 */
			CONNECTED_PREVIOUSLY: string
			/**
			 * A​c​c​e​p​t​ ​c​o​n​n​e​c​t​i​o​n
			 */
			ACCEPT: string
		}
		SHARE_CREDENTIALS: {
			/**
			 * S​h​a​r​e​ ​D​a​t​a
			 */
			NAVBAR_TITLE: string
			/**
			 * r​e​q​u​e​s​t​s​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			DESCRIPTION: string
			/**
			 * R​e​q​u​e​s​t​e​d
			 */
			REQUESTED: string
			/**
			 * A​p​p​r​o​v​e​ ​r​e​q​u​e​s​t
			 */
			APPROVE: string
		}
	}
	CONNECTION: {
		TABS: {
			/**
			 * S​u​m​m​a​r​y
			 */
			SUMMARY: string
			/**
			 * D​a​t​a
			 */
			DATA: string
			/**
			 * A​c​t​i​v​i​t​y
			 */
			ACTIVITY: string
		}
		SUMMARY: {
			/**
			 * N​o​ ​c​o​n​n​e​c​t​i​o​n​s​ ​y​e​t​.
			 */
			EMPTY: string
			/**
			 * C​o​n​n​e​c​t​e​d​ ​t​o
			 */
			TITLE: string
			/**
			 * F​i​r​s​t​ ​c​o​n​n​e​c​t​e​d
			 */
			FIRST_CONNECTED: string
			/**
			 * L​a​s​t​ ​c​o​n​n​e​c​t​e​d
			 */
			LAST_CONNECTED: string
		}
		DATA: {
			/**
			 * N​o​ ​d​a​t​a​ ​y​e​t​.
			 */
			EMPTY: string
		}
	}
	HISTORY: {
		/**
		 * N​o​ ​a​c​t​i​v​i​t​y​ ​y​e​t​.
		 */
		EMPTY: string
		/**
		 * R​e​c​e​i​v​e​d​ ​d​a​t​a​ ​f​r​o​m
		 */
		DATA_RECEIVED: string
		/**
		 * S​h​a​r​e​d​ ​d​a​t​a​ ​w​i​t​h
		 */
		DATA_SHARED: string
		/**
		 * C​o​n​n​e​c​t​e​d​ ​t​o
		 */
		CONNECTION_ADDED: string
	}
	SEARCH: {
		/**
		 * L​o​o​k​ ​f​o​r​ ​s​o​m​e​t​h​i​n​g
		 */
		INPUT_PLACEHOLDER: string
		NO_QUERY: {
			/**
			 * W​h​a​t​ ​s​h​a​l​l​ ​w​e​ ​s​e​a​r​c​h​ ​f​o​r​?
			 */
			TITLE: string
			/**
			 * S​e​a​r​c​h​ ​f​o​r​ ​a​n​y​ ​o​f​ ​y​o​u​r​ ​c​r​e​d​e​n​t​i​a​l​s​ ​a​n​d​ ​b​a​d​g​e​s​ ​h​e​r​e​.
			 */
			DESCRIPTION: string
		}
		NO_RESULTS: {
			/**
			 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d
			 */
			TITLE: string
			/**
			 * T​r​y​ ​s​e​a​r​c​h​i​n​g​ ​f​o​r​ ​s​o​m​e​t​h​i​n​g​ ​e​l​s​e​.
			 */
			DESCRIPTION: string
		}
		/**
		 * R​e​c​e​n​t​ ​s​e​a​r​c​h​e​s
		 */
		RECENT_SEARCHES: string
	}
	CREDENTIAL: {
		/**
		 * C​r​e​d​e​n​t​i​a​l​ ​I​n​f​o​r​m​a​t​i​o​n
		 */
		NAVBAR_TITLE: string
	}
	BADGE: {
		/**
		 * B​a​d​g​e​ ​I​n​f​o​r​m​a​t​i​o​n
		 */
		NAVBAR_TITLE: string
		DETAILS: {
			/**
			 * V​a​l​i​d
			 */
			VALID: string
			/**
			 * I​s​s​u​e​d​ ​b​y
			 */
			ISSUED_BY: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			DESCRIPTION: string
			/**
			 * C​o​n​t​e​n​t​s
			 */
			CONTENTS: string
		}
	}
	SORT: {
		/**
		 * S​o​r​t​i​n​g
		 */
		TITLE: string
		PREFERENCES: {
			/**
			 * L​i​s​t​ ​V​i​e​w
			 */
			LIST_VIEW: string
			/**
			 * G​r​i​d​ ​V​i​e​w
			 */
			GRID_VIEW: string
			/**
			 * A​l​p​h​a​b​e​t​i​c​a​l
			 */
			ALPHABETICAL: string
			/**
			 * D​a​t​e​ ​I​s​s​u​e​d
			 */
			DATE_ISSUED: string
			/**
			 * D​a​t​e​ ​A​d​d​e​d
			 */
			DATE_ADDED: string
		}
		ORDER: {
			/**
			 * A​ ​t​o​ ​Z
			 */
			A_Z: string
			/**
			 * Z​ ​t​o​ ​A
			 */
			Z_A: string
			/**
			 * N​e​w​e​s​t​ ​f​i​r​s​t
			 */
			NEWEST: string
			/**
			 * O​l​d​e​s​t​ ​f​i​r​s​t
			 */
			OLDEST: string
		}
	}
	DOMAIN_LINKAGE: {
		/**
		 * V​e​r​i​f​i​e​d
		 */
		TITLE: string
		/**
		 * U​n​i​M​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​v​e​r​i​f​i​e​d​ ​t​h​e​ ​i​d​e​n​t​i​t​y​ ​t​o​ ​p​r​o​v​i​d​e​ ​y​o​u​ ​w​i​t​h​ ​a​ ​s​e​c​u​r​e​ ​l​o​g​i​n​.
		 */
		SUCCESS: string
		/**
		 * U​n​i​M​e​ ​c​o​u​l​d​ ​n​o​t​ ​v​e​r​i​f​y​ ​t​h​e​ ​l​i​n​k​a​g​e​ ​o​f​ ​t​h​e​ ​i​d​e​n​t​i​t​y​ ​t​o​ ​t​h​e​ ​d​o​m​a​i​n​.
		 */
		FAILURE: string
		/**
		 * U​n​i​M​e​ ​c​o​u​l​d​ ​n​o​t​ ​f​i​n​d​ ​a​n​y​ ​p​r​o​o​f​ ​o​f​ ​t​h​e​ ​d​o​m​a​i​n​'​s​ ​a​s​s​o​c​i​a​t​e​d​ ​i​d​e​n​t​i​t​y​.
		 */
		UNKNOWN: string
		/**
		 * P​r​o​c​e​e​d​ ​w​i​t​h​ ​c​a​u​t​i​o​n​!
		 */
		CAUTION: string
	}
	ERROR: {
		/**
		 * O​o​p​s​!
		 */
		TITLE: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		DEFAULT_MESSAGE: string
	}
	/**
	 * C​a​n​c​e​l
	 */
	CANCEL: string
	/**
	 * C​l​o​s​e
	 */
	CLOSE: string
	/**
	 * C​o​n​t​i​n​u​e
	 */
	CONTINUE: string
	/**
	 * S​k​i​p
	 */
	SKIP: string
	/**
	 * R​e​j​e​c​t
	 */
	REJECT: string
}

export type TranslationFunctions = {
	ONBOARDING: {
		WELCOME: {
			/**
			 * Welcome to
			 */
			GREETING: () => LocalizedString
			/**
			 * UniMe connects your digital world, safely and securely.
			 */
			WHAT_IS_UNIME_1: () => LocalizedString
			/**
			 * Create a brand new identity profile to get started.
			 */
			WHAT_IS_UNIME_2: () => LocalizedString
			/**
			 * Create new profile
			 */
			CREATE_NEW_PROFILE: () => LocalizedString
			/**
			 * Select language
			 */
			SELECT_LANGUAGE: () => LocalizedString
		}
		PLEDGE: {
			/**
			 * UniMe Pledge
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * No funny
			 */
			TITLE_1: () => LocalizedString
			/**
			 * business
			 */
			TITLE_2: () => LocalizedString
			/**
			 * Here's our pledge to you.
			 */
			SUBTITLE: () => LocalizedString
			ITEM_1: {
				/**
				 * We will not share your data
				 */
				TITLE: () => LocalizedString
				/**
				 * Your data belongs to you and only you decide who you share it with. Period. In fact, your data never even touches any of our systems - unless you opt-in to one of the cloud storage options.
				 */
				DESCRIPTION: () => LocalizedString
			}
			ITEM_2: {
				/**
				 * We will not add trackers
				 */
				TITLE: () => LocalizedString
				/**
				 * We do not track your actions behind the scenes. Period. Not for testing or any other reasons. That's our pledge. We also do not collect any anonymous device information or usage statistics. That decision makes developing the app a bit harder for us, but we believe it is the right decision.
				 */
				DESCRIPTION: () => LocalizedString
			}
			ITEM_3: {
				/**
				 * You own your information
				 */
				TITLE: () => LocalizedString
				/**
				 * We believe that it's about time you become the owner of your own personal information again.
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
		TERMS: {
			/**
			 * Terms & Conditions
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * Here's the less interesting
			 */
			TITLE_1: () => LocalizedString
			/**
			 * stuff
			 */
			TITLE_2: () => LocalizedString
			/**
			 * Yeah, we know. We still recommend you read this information carefully.
			 */
			SUBTITLE: () => LocalizedString
			OWNERSHIP: {
				/**
				 * Ownership
				 */
				TITLE: () => LocalizedString
				/**
				 * I understand that I am solely responsible for my data.
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
		CUSTOMIZE: {
			/**
			 * Customization
			 */
			NAVBAR_TITLE: () => LocalizedString
			NAME: {
				/**
				 * Let's go! Choose a
				 */
				TITLE_1: () => LocalizedString
				/**
				 * profile name
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Your profile information will never leave your device.
				 */
				SUBTITLE: () => LocalizedString
				/**
				 * Enter a profile name
				 */
				INPUT_PLACEHOLDER: () => LocalizedString
			}
			PICTURE: {
				/**
				 * Set a display
				 */
				TITLE_1: () => LocalizedString
				/**
				 * picture
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Make it yours.
				 */
				SUBTITLE: () => LocalizedString
			}
		}
		PASSWORD: {
			/**
			 * Password
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * Set your new
			 */
			TITLE_1: () => LocalizedString
			/**
			 * password
			 */
			TITLE_2: () => LocalizedString
			/**
			 * You need to choose a strong password to securely encrypt your data.
			 */
			SUBTITLE: () => LocalizedString
			/**
			 * Enter a password
			 */
			INPUT_PLACEHOLDER: () => LocalizedString
			CONFIRM: {
				/**
				 * Confirm Password
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Please confirm your new
				 */
				TITLE_1: () => LocalizedString
				/**
				 * password
				 */
				TITLE_2: () => LocalizedString
				/**
				 * You need to confirm your password to make sure you typed it correctly.
				 */
				SUBTITLE: () => LocalizedString
				/**
				 * Retype your password
				 */
				INPUT_PLACEHOLDER: () => LocalizedString
				/**
				 * Passwords match
				 */
				MATCH: () => LocalizedString
				/**
				 * Passwords do not match
				 */
				NO_MATCH: () => LocalizedString
			}
			COMPLETED: {
				/**
				 * Password Set
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Your UniMe profile is now
				 */
				TITLE_1: () => LocalizedString
				/**
				 * protected
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Safe & Secure.
				 */
				MESSAGE_1: () => LocalizedString
				/**
				 * Nice Job
				 */
				MESSAGE_2: () => LocalizedString
			}
		}
	}
	SETTINGS: {
		/**
		 * Settings
		 */
		NAVBAR_TITLE: () => LocalizedString
		PROFILE: {
			/**
			 * My profile
			 */
			TITLE: () => LocalizedString
			PROFILE_NAME: {
				/**
				 * Profile name
				 */
				TITLE: () => LocalizedString
				/**
				 * Change profile name
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Enter a profile name
				 */
				INPUT_PLACEHOLDER: () => LocalizedString
				/**
				 * Update
				 */
				CONFIRM: () => LocalizedString
			}
			DISPLAY_PICTURE: {
				/**
				 * Edit
				 */
				EDIT: () => LocalizedString
				/**
				 * Select a profile picture
				 */
				CHANGE: () => LocalizedString
				/**
				 * Remove
				 */
				REMOVE: () => LocalizedString
			}
			DELETE_PROFILE: {
				/**
				 * Delete profile
				 */
				TITLE: () => LocalizedString
			}
		}
		APP: {
			/**
			 * App settings
			 */
			TITLE: () => LocalizedString
			/**
			 * App Settings
			 */
			NAVBAR_TITLE: () => LocalizedString
			LANGUAGE: {
				/**
				 * Language
				 */
				TITLE: () => LocalizedString
				/**
				 * Select Language
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Coming soon
				 */
				COMING_SOON: () => LocalizedString
			}
			THEME: {
				/**
				 * Theme
				 */
				LABEL: () => LocalizedString
				/**
				 * Select Theme
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Choose your app
				 */
				TITLE_1: () => LocalizedString
				/**
				 * appearance
				 */
				TITLE_2: () => LocalizedString
				/**
				 * Are you more of a night owl?
				 */
				SUBTITLE: () => LocalizedString
			}
			PASSWORD: {
				/**
				 * Password
				 */
				TITLE: () => LocalizedString
			}
			ONBOARDING_JOURNEY: {
				/**
				 * Onboarding journey
				 */
				TITLE: () => LocalizedString
				/**
				 * Restart
				 */
				BUTTON_TEXT: () => LocalizedString
			}
			HINTS_AND_TIPS: {
				/**
				 * Hints and tips
				 */
				TITLE: () => LocalizedString
				/**
				 * Reset
				 */
				BUTTON_TEXT: () => LocalizedString
			}
			DEVELOPER_MODE: {
				/**
				 * Developer mode
				 */
				TITLE: () => LocalizedString
			}
		}
		BACKUP_RECOVERY: {
			/**
			 * Backup and recovery
			 */
			TITLE: () => LocalizedString
		}
		LOG_OUT: {
			/**
			 * Log out
			 */
			TITLE: () => LocalizedString
		}
		THEME: {
			/**
			 * System
			 */
			SYSTEM: () => LocalizedString
			/**
			 * Light
			 */
			LIGHT: () => LocalizedString
			/**
			 * Dark
			 */
			DARK: () => LocalizedString
		}
		PASSWORD: {
			POLICY: {
				/**
				 * Your password must contain
				 */
				TITLE: () => LocalizedString
				/**
				 * uppercase letter
				 */
				UPPERCASE_LETTER: () => LocalizedString
				/**
				 * lowercase letter
				 */
				LOWERCASE_LETTER: () => LocalizedString
				/**
				 * number
				 */
				NUMBER: () => LocalizedString
				/**
				 * characters
				 */
				CHARACTERS: () => LocalizedString
			}
		}
		RESET_APP: {
			/**
			 * Reset app
			 */
			TITLE: () => LocalizedString
			/**
			 * Are you sure you want to reset the app and remove all data?
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Yes, delete everything
			 */
			CONFIRM: () => LocalizedString
			/**
			 * No, keep my profile
			 */
			CANCEL: () => LocalizedString
		}
		/**
		 * Account
		 */
		ACCOUNT: () => LocalizedString
		SUPPORT: {
			/**
			 * Support
			 */
			TITLE: () => LocalizedString
			ABOUT: {
				/**
				 * About UniMe
				 */
				TITLE: () => LocalizedString
				/**
				 * About UniMe
				 */
				NAVBAR_TITLE: () => LocalizedString
				/**
				 * Specifications
				 */
				SPECIFICATIONS: () => LocalizedString
				/**
				 * Version
				 */
				VERSION: () => LocalizedString
				/**
				 * License
				 */
				LICENSE: () => LocalizedString
				/**
				 * Built with Tauri
				 */
				BUILT_WITH: () => LocalizedString
			}
			FEEDBACK: {
				/**
				 * Send feedback
				 */
				TITLE: () => LocalizedString
			}
		}
	}
	LOCK_SCREEN: {
		/**
		 * Enter your password
		 */
		PASSWORD_INPUT_PLACEHOLDER: () => LocalizedString
		/**
		 * Unlock wallet
		 */
		BUTTON_TEXT: () => LocalizedString
		/**
		 * Forgot password?
		 */
		FORGOT_PASSWORD: () => LocalizedString
	}
	ME: {
		/**
		 * Me
		 */
		BOTTOM_NAVIGATION_TITLE: () => LocalizedString
		GREETINGS: {
			/**
			 * Hey
			 */
			GREETING_0: () => LocalizedString
			/**
			 * What's up
			 */
			GREETING_1: () => LocalizedString
			/**
			 * How are you
			 */
			GREETING_2: () => LocalizedString
			/**
			 * Welcome back
			 */
			GREETING_3: () => LocalizedString
			/**
			 * Hello
			 */
			GREETING_4: () => LocalizedString
		}
		/**
		 * Visit one of the following websites on a desktop computer to get started.
		 */
		DEMO: () => LocalizedString
		CREDENTIAL_TABS: {
			/**
			 * All
			 */
			ALL: () => LocalizedString
			/**
			 * Data
			 */
			DATA: () => LocalizedString
			/**
			 * Badges
			 */
			BADGES: () => LocalizedString
		}
		EMPTY_CREDENTIALS: {
			/**
			 * It's a bit quiet in here
			 */
			TITLE: () => LocalizedString
			/**
			 * Why not add some credentials to start your new digital me?
			 */
			SUBTITLE: () => LocalizedString
		}
		/**
		 * My favorites
		 */
		FAVORITES: () => LocalizedString
	}
	ACTIVITY: {
		/**
		 * Activity
		 */
		BOTTOM_NAVIGATION_TITLE: () => LocalizedString
		/**
		 * Connected
		 */
		NAVBAR_TITLE: () => LocalizedString
		TABS: {
			/**
			 * Connections
			 */
			CONNECTIONS: () => LocalizedString
			/**
			 * History
			 */
			HISTORY: () => LocalizedString
		}
	}
	SCAN: {
		/**
		 * Scan
		 */
		BOTTOM_NAVIGATION_TITLE: () => LocalizedString
		/**
		 * Scan a
		 */
		TITLE_1: () => LocalizedString
		/**
		 * QR Code
		 */
		TITLE_2: () => LocalizedString
		/**
		 * Bring a QR Code into view of this screen to start an interaction.
		 */
		SUBTITLE: () => LocalizedString
		/**
		 * No permission to access the camera
		 */
		PERMISSION_DENIED: () => LocalizedString
		/**
		 * Open settings
		 */
		OPEN_SETTINGS: () => LocalizedString
		CREDENTIAL_OFFER: {
			/**
			 * Credential Offer
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * is offering you the following credentials
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Accept credentials
			 */
			ACCEPT: () => LocalizedString
		}
		CONNECTION_REQUEST: {
			/**
			 * Connection Request
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * New connection
			 */
			TITLE: () => LocalizedString
			/**
			 * Only accept new connections that you recognize and trust
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Connected previously
			 */
			CONNECTED_PREVIOUSLY: () => LocalizedString
			/**
			 * Accept connection
			 */
			ACCEPT: () => LocalizedString
		}
		SHARE_CREDENTIALS: {
			/**
			 * Share Data
			 */
			NAVBAR_TITLE: () => LocalizedString
			/**
			 * requests the following credentials
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Requested
			 */
			REQUESTED: () => LocalizedString
			/**
			 * Approve request
			 */
			APPROVE: () => LocalizedString
		}
	}
	CONNECTION: {
		TABS: {
			/**
			 * Summary
			 */
			SUMMARY: () => LocalizedString
			/**
			 * Data
			 */
			DATA: () => LocalizedString
			/**
			 * Activity
			 */
			ACTIVITY: () => LocalizedString
		}
		SUMMARY: {
			/**
			 * No connections yet.
			 */
			EMPTY: () => LocalizedString
			/**
			 * Connected to
			 */
			TITLE: () => LocalizedString
			/**
			 * First connected
			 */
			FIRST_CONNECTED: () => LocalizedString
			/**
			 * Last connected
			 */
			LAST_CONNECTED: () => LocalizedString
		}
		DATA: {
			/**
			 * No data yet.
			 */
			EMPTY: () => LocalizedString
		}
	}
	HISTORY: {
		/**
		 * No activity yet.
		 */
		EMPTY: () => LocalizedString
		/**
		 * Received data from
		 */
		DATA_RECEIVED: () => LocalizedString
		/**
		 * Shared data with
		 */
		DATA_SHARED: () => LocalizedString
		/**
		 * Connected to
		 */
		CONNECTION_ADDED: () => LocalizedString
	}
	SEARCH: {
		/**
		 * Look for something
		 */
		INPUT_PLACEHOLDER: () => LocalizedString
		NO_QUERY: {
			/**
			 * What shall we search for?
			 */
			TITLE: () => LocalizedString
			/**
			 * Search for any of your credentials and badges here.
			 */
			DESCRIPTION: () => LocalizedString
		}
		NO_RESULTS: {
			/**
			 * No results found
			 */
			TITLE: () => LocalizedString
			/**
			 * Try searching for something else.
			 */
			DESCRIPTION: () => LocalizedString
		}
		/**
		 * Recent searches
		 */
		RECENT_SEARCHES: () => LocalizedString
	}
	CREDENTIAL: {
		/**
		 * Credential Information
		 */
		NAVBAR_TITLE: () => LocalizedString
	}
	BADGE: {
		/**
		 * Badge Information
		 */
		NAVBAR_TITLE: () => LocalizedString
		DETAILS: {
			/**
			 * Valid
			 */
			VALID: () => LocalizedString
			/**
			 * Issued by
			 */
			ISSUED_BY: () => LocalizedString
			/**
			 * Description
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * Contents
			 */
			CONTENTS: () => LocalizedString
		}
	}
	SORT: {
		/**
		 * Sorting
		 */
		TITLE: () => LocalizedString
		PREFERENCES: {
			/**
			 * List View
			 */
			LIST_VIEW: () => LocalizedString
			/**
			 * Grid View
			 */
			GRID_VIEW: () => LocalizedString
			/**
			 * Alphabetical
			 */
			ALPHABETICAL: () => LocalizedString
			/**
			 * Date Issued
			 */
			DATE_ISSUED: () => LocalizedString
			/**
			 * Date Added
			 */
			DATE_ADDED: () => LocalizedString
		}
		ORDER: {
			/**
			 * A to Z
			 */
			A_Z: () => LocalizedString
			/**
			 * Z to A
			 */
			Z_A: () => LocalizedString
			/**
			 * Newest first
			 */
			NEWEST: () => LocalizedString
			/**
			 * Oldest first
			 */
			OLDEST: () => LocalizedString
		}
	}
	DOMAIN_LINKAGE: {
		/**
		 * Verified
		 */
		TITLE: () => LocalizedString
		/**
		 * UniMe successfully verified the identity to provide you with a secure login.
		 */
		SUCCESS: () => LocalizedString
		/**
		 * UniMe could not verify the linkage of the identity to the domain.
		 */
		FAILURE: () => LocalizedString
		/**
		 * UniMe could not find any proof of the domain's associated identity.
		 */
		UNKNOWN: () => LocalizedString
		/**
		 * Proceed with caution!
		 */
		CAUTION: () => LocalizedString
	}
	ERROR: {
		/**
		 * Oops!
		 */
		TITLE: () => LocalizedString
		/**
		 * Something went wrong. Please try again.
		 */
		DEFAULT_MESSAGE: () => LocalizedString
	}
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Close
	 */
	CLOSE: () => LocalizedString
	/**
	 * Continue
	 */
	CONTINUE: () => LocalizedString
	/**
	 * Skip
	 */
	SKIP: () => LocalizedString
	/**
	 * Reject
	 */
	REJECT: () => LocalizedString
}

export type Formatters = {}
