// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from "./Connection";
import type { CurrentUserPrompt } from "./CurrentUserPrompt";
import type { DisplayCredential } from "./display-credential/DisplayCredential";
import type { Locale } from "./Locale";
import type { Profile } from "./Profile";

export interface AppState { active_profile: Profile | null, locale: Locale, credentials: Array<DisplayCredential>, current_user_prompt: CurrentUserPrompt | null, dev_mode_enabled: boolean, debug_messages: Array<string>, user_journey: object | null, connections: Array<Connection>, user_data_query: Array<string>, }