// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialDisplay } from "./CredentialDisplay";

export interface CredentialMetadata { is_favorite: boolean, display: CredentialDisplay, }