// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialMetadata } from "./CredentialMetadata";

export interface DisplayCredential { id: string, issuer_name: string | null, format: string, data: object, metadata: CredentialMetadata, }