// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface EmailVerification { email: string, label: string, verification_id: string | null, expires_at: string | null, validation_expiration_in_secs: number | null, error: string | null, }