// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryTarget } from "../QueryTarget";

export interface AddRecent { target: QueryTarget, search_hit: string, }