// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTheme } from "../AppTheme";

export interface CreateNew { name: string, picture: string, theme: AppTheme, password: string, }