// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryTarget } from "../QueryTarget";

export interface DeleteRecentSearch { delete_target: QueryTarget, search_term: string, }