// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileSteps } from "../dev/ProfileSteps";
import type { ProfileType } from "../dev/ProfileType";

export interface DevProfile { profile: ProfileType, execute_steps: ProfileSteps | null, }