// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileSteps } from "./DevProfileSteps";
import type { ProfileType } from "./DevProfileType";

export interface DevProfile { profile: ProfileType, execute_steps: ProfileSteps | null, }