// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSteps = "CreateProfile" | "AddCredentials" | "AcceptCredentials" | "AddConnection" | "AcceptConnection" | "AddPresentation" | "ShareCredentails" | "AddFutureEngineer" | "CompleteFlow";