// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfIssuedCredentialType } from "../credentials/SelfIssuedCredentialType";

export interface SelfIssueCredential { type: SelfIssuedCredentialType, data: object, is_favorite: boolean, icon?: string, }