// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSortMethod } from "../profile_settings/ConnectionSortMethod";
import type { CredentialSortMethod } from "../profile_settings/CredentialSortMethod";

export interface UpdateSortingPreference { credential_sorting?: CredentialSortMethod, connection_sorting?: ConnectionSortMethod, reverse?: boolean, }