// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSorting } from "../ConnectionSorting";
import type { CredentialSorting } from "../CredentialSorting";

export interface UpdateSortingPreference { credential_sorting: CredentialSorting | null, connection_sorting: ConnectionSorting | null, }