// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSortMethod } from "../ConnectionSortMethod";
import type { CredentialSortMethod } from "../CredentialSortMethod";

export interface UpdateSortingPreference { credential_sorting?: CredentialSortMethod, connection_sorting?: ConnectionSortMethod, reverse?: boolean }
