// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateCredentialMetadata { id: string, name?: string, icon?: string, color?: string, is_favorite?: boolean, }