// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionType = "[App] Get state" | "[App] Reset" | "[DID] Create new" | "[Settings] Set locale" | "[DEV] Load profile" | "[Authenticate] Get request" | "[Authenticate] Send response";