// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Connection { client_name: string, url: string, logo_uri: string, verified: boolean, first_connected: string, last_connected: string, }