// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";
import type { StateStatus } from "./StateStatus";

export interface TransferState { status: StateStatus, active_profile: Profile | null, locale: string, }