// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";

export interface TransferState { active_profile: Profile | null, locale: string, credentials: any }