// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimType } from "./ClaimType";
import type { Profile } from "./Profile";

export interface TransferState { active_profile: Profile | null, active_authentication_request: Map<string, string>, active_requested_claims: Record<string, ClaimType> | null, locale: string, }