// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryTarget } from "./QueryTarget";
import type { SortMethod } from "./SortMethod";

export interface UserDataQuery { target: QueryTarget, search_term: string | null, sort_method: SortMethod | null, sort_reverse: boolean | null, }