// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSteps = "Create profile" | "Add credentials" | "Accept credentials" | "Add connection" | "Accept connection" | "Add presentation" | "Share credentials" | "Add future engineer" | "Complete flow";