// This file was generated by [ts-rs](https://.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventType } from "./EventType";
import type { HistoryCredential } from "./HistoryCredential";

export interface HistoryEvent { connection_id: string, connection_name: string, event_type: EventType, date: string, credentials: Array<HistoryCredential>, }