[package]
name = "unime"
version = "0.10.0"
description = "Identity Wallet for people to manage Decentralized Identities and Verifiable Credentials"
homepage = "https://www.impierce.com/"
authors = ["Impierce Technologies"]
keywords = ["identity", "did", "ssi", "wallet", "siopv2"]
license = "Apache-2.0"
repository = "https://github.com/impierce/identity-wallet"
edition = "2021"
rust-version.workspace = true

[lib]
name = "unime"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true

dotenvy = { version = "0.15" }
identity-wallet = { path = "../../identity-wallet" }
iota-sdk = { git = "https://github.com/impierce/iota", package = "iota-sdk", branch = "temp/fix" }
jni = "0.21"
log.workspace = true
rustls.workspace = true
rustls-platform-verifier.workspace = true
serde_json.workspace = true
tauri-plugin-barcode-scanner = { version = "2" }
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
tauri-plugin-biometric = { version = "2" }
tauri-plugin-deep-link = { version = "2" }
tauri-plugin-fs = { version = "2" }
tauri-plugin-keystore = { version = "2.1.0-alpha.1" }
tauri-plugin-log = { version = "2", features = ["colored"] }
tauri-plugin-opener = { version = "2" }
tauri-plugin-os = { version = "2" }
tauri-plugin-shell = { version = "2" }
[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }

[dev-dependencies]
tauri = { workspace = true, features = ["test"] }
unime = { path = ".", features = ["test_utils"] }

did_manager.workspace = true
identity-wallet = { path = "../../identity-wallet", features = ["test_utils"] }
jsonwebtoken.workspace = true
oid4vc.workspace = true
rand.workspace = true
serde = { version = "1.0", features = ["derive"] }
serial_test.workspace = true
tempfile.workspace = true
tokio.workspace = true
typetag = "0.2"
url = "2.4"
wiremock.workspace = true

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
test_utils = []
