// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CredentialSortMethod = "name_az" | "issue_date_new_old" | "added_date_new_old";