// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locale } from "./Locale";
import type { Profile } from "./Profile";
import type { SortingPreferences } from "./SortingPreferences";

export interface ProfileSettings { locale: Locale, profile: Profile | null, preferred_did_methods: Array<string>, preferred_key_types: Array<string>, sorting_preferences: SortingPreferences, }