// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ClientMetadata { client_name: string, logo_uri: string | null, connection_url: string, redirect_uri: string | null, client_id: string, }