// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEvent } from "../history/HistoryEvent";

export interface ConnectionData { first_interacted_at: string, last_interacted_at: string, interactions: Array<HistoryEvent>, }