// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from "./Member";

export interface EcosystemProfile { logo_uri: string | null, name: string, description: string | null, ecosystem_leader: Member, member_count: number, members: Array<Member>, }