// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayCredential } from "../credentials/DisplayCredential";
import type { ValidationResult } from "./ValidationResult";

export interface LinkedVerifiableCredentialData { credential: DisplayCredential, issuer_domain_validations: Array<ValidationResult>, }