// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TrustList { id: string, display_name: string, owned: boolean, entries: Record<string, boolean>, }