// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Offer } from "./Offer";
import type { Redirect } from "./Redirect";
import type { Selection } from "./Selection";
import type { Warning } from "./Warning";

export type CurrentUserFlow = Redirect | Warning | Selection | Offer;