// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentUserFlowType } from "./CurrentUserFlowType";

export interface Selection { type: CurrentUserFlowType, options: Array<string>, }