name: Publish to CrabNebula Cloud

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CN_APPLICATION: "impierce/unime"

jobs:
  draft:
    name: Draft Release
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: create draft release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release draft ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  build_android:
    name: Build Android App Bundle
    needs: draft

    # ubuntu-latest: x64_2-core-7gb
    runs-on: linux-x64_16-core-64gb

    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: setup Android SDK
        uses: android-actions/setup-android@v3

      - name: setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          link-to-sdk: true

      - name: install Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      # required to build `aws-lc-sys`
      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libclang-dev clang
          cargo install --force --locked bindgen-cli

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: initialize Android target
        working-directory: unime
        run: |
          pnpm install
          pnpm tauri android init

      - name: setup Android signing
        working-directory: unime/src-tauri/gen/android
        run: |
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: build Tauri app for Android
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          BINDGEN_EXTRA_CLANG_ARGS: "--sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          PUBLIC_DEV_MODE_MENU_EXPANDED: false
          PUBLIC_DEV_SHOW_CURRENT_ROUTE: false
          PUBLIC_STYLE_SAFE_AREA_INSETS: false
        run: pnpm tauri android build --aab true

      - name: upload assets
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release upload ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}
          path: ./src-tauri

  build_ios:
    name: Build iOS App
    needs: draft

    # macos-latest: M1 (3 cores), 7 GB, arm64
    # macos-latest-xlarge: M2 (5 cores), 14 GB, arm64
    runs-on: macos-15-xlarge

    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: install iOS target
        run: rustup target add aarch64-apple-ios

      # required to build `aws-lc-sys`
      - name: install bindgen-cli
        run: cargo install --force --locked bindgen-cli

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.3"

      - name: setup Apple API key
        run: |
          APPLE_API_KEY_PATH="$RUNNER_TEMP/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8"
          base64 -d <<< "${{ secrets.APPLE_API_KEY_BASE64 }}" > $APPLE_API_KEY_PATH
          echo "APPLE_API_KEY_PATH=$APPLE_API_KEY_PATH" >> $GITHUB_ENV
          echo "API_PRIVATE_KEYS_DIR=$RUNNER_TEMP" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: initialize iOS target
        working-directory: unime
        run: |
          pnpm install
          pnpm tauri ios init

      - name: build Tauri app for iOS
        env:
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_DEVELOPMENT_TEAM: "Impierce Technologies B.V."
          PUBLIC_DEV_MODE_MENU_EXPANDED: false
          PUBLIC_DEV_SHOW_CURRENT_ROUTE: false
          PUBLIC_STYLE_SAFE_AREA_INSETS: false
        run: pnpm tauri ios build --export-method app-store-connect

      - name: upload assets
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release upload ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  # Publishing is done manually from the CrabNebula Cloud Dashboard

  # publish:
  #   needs: [build_android, build_ios]

  #   runs-on: ubuntu-latest

  #   environment: production

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: publish release
  #       uses: crabnebula-dev/cloud-release@v0
  #       with:
  #         command: release publish ${{ env.CN_APPLICATION }} --framework tauri
  #         api-key: ${{ secrets.CN_API_KEY }}
