name: Format, Lint, Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  unime_frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      working-directory: ./unime
      run: npm install    
    - name: Format
      working-directory: ./unime
      run: npm run format:check
    # TODO: enable liniting for frontend  
    # - name: Lint
    #   working-directory: ./unime
    #   run: npm run lint
    - name: Test
      working-directory: ./unime
      run: npx vitest run
  
  unime_core:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Format
      working-directory: ./unime
      run: cargo fmt --all -- --check
    - name: Lint
      working-directory: ./unime
      run: cargo clippy --all-targets --all-features
      # TODO: add "-- -D warnings" to make clippy fail on warnings
    - name: Test
      working-directory: ./unime
      run: cargo test
      #run: cargo test --all
