name: Format, Lint, Test

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      working-directory: ./unime
      run: npm install    
    - name: Format
      working-directory: ./unime
      run: npm run format:check
    # - name: Lint
    #   working-directory: ./unime
    #   run: npm run lint
    - name: Test (frontend)
      working-directory: ./unime
      run: npx vitest run
